use r2il::R2ILBlock;
use r2ssa::{CFGRiskSummary, SSAFunction, SsaArtifact};
use r2types::FunctionTypeFacts;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SemanticRoutePlan {
    Standard,
    StructuredWorker { reason: String },
    LinearWorker { reason: String },
    FallbackComment { comment: String },
}

pub(crate) fn prefer_symbolic_large_worker_decompile(
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
) -> bool {
    let Some(semantic_artifact) = semantic_artifact else {
        return false;
    };
    matches!(
        semantic_artifact.decompile_plan(),
        r2sym::DecompilePlan::Ready
    ) && semantic_artifact.diagnostics.skipped_large_cfg
        && matches!(
            semantic_artifact.stage,
            r2sym::RefinementStage::Residual | r2sym::RefinementStage::Compiled
        )
        && semantic_artifact
            .native_body()
            .is_some_and(|body| matches!(body.summary.slice_class, r2sym::SliceClass::Worker))
        && semantic_artifact
            .native_body()
            .is_some_and(|body| !body.regions.is_empty())
}

pub(crate) fn should_skip_runtime_type_inference(
    prepared: Option<&SsaArtifact>,
    _type_facts: &FunctionTypeFacts,
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
) -> bool {
    if prefer_symbolic_large_worker_decompile(semantic_artifact) {
        return true;
    }
    let Some(prepared) = prepared else {
        return false;
    };
    let summary = prepared.function().cfg_risk_summary();
    summary.block_count >= 96
        && summary.switch_block_count > 0
        && summary.max_switch_cases >= 32
        && summary.back_edge_count == 0
}

pub(crate) fn should_use_prepared_semantic_view(
    prepared: Option<&SsaArtifact>,
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
) -> bool {
    prepared.is_some() && !prefer_symbolic_large_worker_decompile(semantic_artifact)
}

pub(crate) fn preferred_semantic_fallback_comment(
    func_name: &str,
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
) -> Option<String> {
    let semantic_artifact = semantic_artifact?;
    if matches!(semantic_artifact.execution, r2sym::ExecutionModel::Vm) {
        return crate::consumer_fallback::semantic_fallback_comment(
            func_name,
            Some(semantic_artifact),
        );
    }
    if !crate::is_autogenerated_function_name(func_name) {
        return None;
    }
    if matches!(
        semantic_artifact.decompile_plan(),
        r2sym::DecompilePlan::Ready
    ) {
        return None;
    }
    if semantic_artifact.diagnostics.skipped_large_cfg {
        return crate::consumer_fallback::semantic_fallback_comment(
            func_name,
            Some(semantic_artifact),
        );
    }
    semantic_artifact
        .diagnostics
        .residual_reasons
        .contains(&r2sym::ResidualReason::InterpreterRequiresStepSummary)
        .then(|| {
            crate::consumer_fallback::semantic_fallback_comment(func_name, Some(semantic_artifact))
        })
        .flatten()
}

pub(crate) fn preferred_semantic_linearization_reason(
    func_name: &str,
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
    cfg_summary: &CFGRiskSummary,
) -> Option<String> {
    let semantic_artifact = semantic_artifact?;
    if !crate::is_autogenerated_function_name(func_name) {
        return None;
    }
    if !matches!(
        semantic_artifact.decompile_plan(),
        r2sym::DecompilePlan::Ready
    ) || !semantic_artifact.diagnostics.skipped_large_cfg
    {
        return None;
    }
    if semantic_artifact.supports_guarded_structuring() {
        return None;
    }
    if semantic_artifact
        .native_body()
        .is_none_or(|body| body.regions.is_empty())
    {
        return None;
    }
    Some(preferred_semantic_worker_reason(cfg_summary))
}

pub(crate) fn preferred_semantic_structuring_reason(
    func_name: &str,
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
    cfg_summary: &CFGRiskSummary,
) -> Option<String> {
    let semantic_artifact = semantic_artifact?;
    if !crate::is_autogenerated_function_name(func_name) {
        return None;
    }
    if !matches!(
        semantic_artifact.decompile_plan(),
        r2sym::DecompilePlan::Ready
    ) {
        return None;
    }
    if !semantic_artifact.supports_guarded_structuring()
        || !semantic_artifact.diagnostics.skipped_large_cfg
    {
        return None;
    }
    Some(preferred_semantic_worker_reason(cfg_summary))
}

pub(crate) fn preferred_semantic_worker_reason(cfg_summary: &CFGRiskSummary) -> String {
    cfg_guard_reason_from_summary(cfg_summary)
        .unwrap_or_else(|| "semantic worker islands".to_string())
}

pub fn cfg_guard_reason_from_summary(summary: &CFGRiskSummary) -> Option<String> {
    if summary.loop_count > 8 || summary.back_edge_count > 16 {
        return Some(format!(
            "complex loop graph (loops={}, back_edges={})",
            summary.loop_count, summary.back_edge_count
        ));
    }

    if summary.loop_count > 4 && summary.block_count >= 96 && summary.max_switch_cases >= 32 {
        return Some(format!(
            "large dense switch in looped CFG (blocks={}, loops={}, max_switch_cases={})",
            summary.block_count, summary.loop_count, summary.max_switch_cases
        ));
    }

    None
}

pub fn cfg_guard_reason(blocks: &[R2ILBlock]) -> Option<String> {
    let ssa_func = SSAFunction::from_blocks_raw_no_arch(blocks)?;
    cfg_guard_reason_from_summary(&ssa_func.cfg_risk_summary())
}

pub fn block_guard_fallback_comment(func_name: &str, blocks: usize, max_blocks: usize) -> String {
    format!(
        "/* r2dec fallback: skipped decompilation for {} ({} blocks > limit {}). Set SLEIGH_DEC_MAX_BLOCKS to override. */",
        func_name, blocks, max_blocks
    )
}

pub fn artifact_guard_fallback_comment(func_name: &str, reason: &str) -> String {
    format!(
        "/* r2dec fallback: skipped decompilation for {} ({}) */",
        func_name, reason
    )
}

pub fn semantic_route_plan(
    func_name: &str,
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
    cfg_summary: &CFGRiskSummary,
) -> SemanticRoutePlan {
    if let Some(comment) = preferred_semantic_fallback_comment(func_name, semantic_artifact) {
        return SemanticRoutePlan::FallbackComment { comment };
    }
    if let Some(reason) =
        preferred_semantic_structuring_reason(func_name, semantic_artifact, cfg_summary)
    {
        return SemanticRoutePlan::StructuredWorker { reason };
    }
    if let Some(reason) =
        preferred_semantic_linearization_reason(func_name, semantic_artifact, cfg_summary)
    {
        return SemanticRoutePlan::LinearWorker { reason };
    }
    SemanticRoutePlan::Standard
}

pub fn detached_semantic_route_plan(
    func_name: &str,
    blocks: &[R2ILBlock],
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
) -> Option<SemanticRoutePlan> {
    let ssa_func = SSAFunction::from_blocks_raw_no_arch(blocks)?;
    Some(semantic_route_plan(
        func_name,
        semantic_artifact,
        &ssa_func.cfg_risk_summary(),
    ))
}

pub fn detached_semantic_linearization_reason(
    func_name: &str,
    blocks: &[R2ILBlock],
    semantic_artifact: Option<&r2sym::SemanticArtifact>,
) -> Option<String> {
    match detached_semantic_route_plan(func_name, blocks, semantic_artifact)? {
        SemanticRoutePlan::LinearWorker { reason } => Some(reason),
        _ => None,
    }
}
