#[cfg(test)]
use r2il::R2ILBlock;
#[cfg(test)]
use r2ssa::{CFGRiskSummary, SSAFunction};
#[cfg(test)]
use r2types::{DecompileCapabilityView, FunctionFacts};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SemanticRoutePlan {
    Standard,
    StructuredWorker { reason: String },
    SummaryIslands { reason: String },
    LinearWorker { reason: String },
    VmSummary { reason: String },
    FallbackComment { comment: String },
}

#[cfg(test)]
fn decompile_capability(function_facts: &FunctionFacts) -> DecompileCapabilityView {
    function_facts.decompile_capability()
}

#[cfg(test)]
fn has_generic_only_summary_islands(capability: &DecompileCapabilityView) -> bool {
    capability.has_summary_islands && !capability.has_primary_summary_islands
}

#[cfg(test)]
fn has_large_bounded_memory_summary_worker(capability: &DecompileCapabilityView) -> bool {
    capability.skipped_large_cfg
        && capability.has_memory_read_write_summary_pair
        && matches!(
            capability.slice_class,
            Some(r2sym::SliceClass::Worker | r2sym::SliceClass::GenericLarge)
        )
}

#[cfg(test)]
fn has_dense_summary_only_memory_worker(capability: &DecompileCapabilityView) -> bool {
    !capability.has_native_regions
        && capability.has_memory_read_write_summary_pair
        && capability.summary_island_count >= 24
        && matches!(
            capability.slice_class,
            Some(r2sym::SliceClass::Worker | r2sym::SliceClass::GenericLarge)
        )
}

#[cfg(test)]
fn has_weak_summary_arg_contract_conflict(function_facts: &FunctionFacts) -> bool {
    let Some(signature) = function_facts.types.merged_signature.as_ref() else {
        return false;
    };
    let Some(native) = function_facts
        .semantic_artifact()
        .and_then(r2sym::SemanticArtifact::native_body)
    else {
        return false;
    };
    let param_count = signature.params.len();
    let weak_worker_conflict = native.summary.worker_summaries.iter().any(|summary| {
        !summary.evidence.allows_guarded_structuring()
            && summary
                .arg_indices()
                .into_iter()
                .any(|index| index >= param_count)
    });
    let weak_region_conflict = native.summary.region_summaries.iter().any(|summary| {
        !summary.evidence.allows_guarded_structuring()
            && summary
                .arg_indices()
                .into_iter()
                .any(|index| index >= param_count)
    });
    weak_worker_conflict || weak_region_conflict
}

#[cfg(test)]
pub(crate) fn preferred_semantic_fallback_comment(
    func_name: &str,
    function_facts: &FunctionFacts,
) -> Option<String> {
    let capability = decompile_capability(function_facts);
    if !crate::is_autogenerated_function_name(func_name) {
        return None;
    }
    if capability
        .plan
        .as_ref()
        .is_some_and(r2sym::DecompilePlan::allows_native_linearization)
    {
        return None;
    }
    if capability.skipped_large_cfg {
        return crate::consumer_fallback::semantic_fallback_comment(func_name, function_facts);
    }
    capability
        .residual_reasons
        .contains(&r2sym::ResidualReason::InterpreterRequiresStepSummary)
        .then(|| crate::consumer_fallback::semantic_fallback_comment(func_name, function_facts))
        .flatten()
}

#[cfg(test)]
pub(crate) fn preferred_vm_summary_reason(function_facts: &FunctionFacts) -> Option<String> {
    match function_facts.decompile_plan()? {
        r2sym::DecompilePlan::VmSummaryOnly { reason } => Some(reason),
        _ => None,
    }
}

#[cfg(test)]
fn semantic_route_from_artifact_plan(
    semantic_artifact: &r2sym::SemanticArtifact,
) -> Option<SemanticRoutePlan> {
    match semantic_artifact.decompile_plan() {
        r2sym::DecompilePlan::NativeLinear { reason }
            if native_linear_artifact_plan_allows_summary_route(semantic_artifact) =>
        {
            Some(SemanticRoutePlan::LinearWorker { reason })
        }
        r2sym::DecompilePlan::NativeSummaryIslands { reason } => {
            Some(SemanticRoutePlan::SummaryIslands { reason })
        }
        r2sym::DecompilePlan::VmSummaryOnly { reason } => {
            Some(SemanticRoutePlan::VmSummary { reason })
        }
        _ => None,
    }
}

#[cfg(test)]
fn native_linear_artifact_plan_allows_summary_route(
    semantic_artifact: &r2sym::SemanticArtifact,
) -> bool {
    let Some(native) = semantic_artifact.native_body() else {
        return false;
    };
    let summary_count =
        native.summary.region_summaries.len() + native.summary.worker_summaries.len();
    let has_specific_summary = native.has_memory_read_write_summary_pair()
        || native.summary.worker_summaries.iter().any(|summary| {
            !matches!(
                summary.kind,
                r2sym::NativeWorkerSummaryKind::MemoryRead
                    | r2sym::NativeWorkerSummaryKind::MemoryWrite
                    | r2sym::NativeWorkerSummaryKind::Unknown
            )
        });
    summary_count >= 8
        && has_specific_summary
        && matches!(
            semantic_artifact.slice_class(),
            Some(
                r2sym::SliceClass::Worker
                    | r2sym::SliceClass::GenericLarge
                    | r2sym::SliceClass::Wrapper
            )
        )
}

#[cfg(test)]
pub(crate) fn preferred_semantic_linearization_reason(
    func_name: &str,
    function_facts: &FunctionFacts,
    cfg_summary: &CFGRiskSummary,
) -> Option<String> {
    let capability = decompile_capability(function_facts);
    let plan = capability.plan.as_ref()?;
    if let r2sym::DecompilePlan::NativeLinear { reason } = plan
        && capability.has_native_regions
        && (!capability.skipped_large_cfg || !crate::is_autogenerated_function_name(func_name))
        && matches!(capability.slice_class, Some(r2sym::SliceClass::Worker))
        && !capability.assumption_conflicted
        && capability.ambiguous_targets.is_empty()
        && (!has_generic_only_summary_islands(&capability) || capability.skipped_large_cfg)
    {
        return Some(reason.clone());
    }
    if let r2sym::DecompilePlan::NativeLinear { reason } = plan
        && capability.has_summary_islands
        && capability.has_primary_summary_islands
        && !capability.has_native_regions
        && matches!(
            capability.slice_class,
            Some(r2sym::SliceClass::Worker | r2sym::SliceClass::GenericLarge)
        )
        && !has_weak_summary_arg_contract_conflict(function_facts)
        && !capability.assumption_conflicted
        && !capability.summary_conflicted
        && capability.ambiguous_targets.is_empty()
    {
        return Some(reason.clone());
    }
    if !crate::is_autogenerated_function_name(func_name) {
        return None;
    }
    let downgraded_from_structured = matches!(plan, r2sym::DecompilePlan::NativeStructured)
        && (capability.assumption_conflicted
            || capability.summary_conflicted
            || !capability.ambiguous_targets.is_empty());
    let linear_ready =
        matches!(plan, r2sym::DecompilePlan::NativeLinear { .. }) || downgraded_from_structured;
    if !linear_ready || !capability.skipped_large_cfg || !capability.has_native_regions {
        return None;
    }
    Some(preferred_semantic_worker_reason(cfg_summary))
}

#[cfg(test)]
pub(crate) fn preferred_semantic_summary_islands_reason(
    function_facts: &FunctionFacts,
    cfg_summary: &CFGRiskSummary,
) -> Option<String> {
    let capability = decompile_capability(function_facts);
    if has_weak_summary_arg_contract_conflict(function_facts) {
        return None;
    }
    let large_bounded_memory_worker = has_large_bounded_memory_summary_worker(&capability);
    let dense_summary_only_memory_worker = has_dense_summary_only_memory_worker(&capability);
    if !capability.has_summary_islands
        || (!capability.has_primary_summary_islands
            && !large_bounded_memory_worker
            && !dense_summary_only_memory_worker)
        || !matches!(
            capability.slice_class,
            Some(r2sym::SliceClass::Worker | r2sym::SliceClass::GenericLarge)
        )
    {
        return None;
    }
    match capability.plan.as_ref()? {
        r2sym::DecompilePlan::NativeStructured => {
            if capability.skipped_large_cfg
                && (cfg_guard_reason_from_summary(cfg_summary).is_some()
                    || capability.primary_summary_island_count >= 8
                    || large_bounded_memory_worker)
            {
                return Some(preferred_semantic_worker_reason(cfg_summary));
            }
            let summary_dense_native_worker = capability.primary_summary_island_count >= 16
                && (cfg_summary.loop_count > 0
                    || cfg_summary.back_edge_count > 0
                    || capability.actionable_region_count >= 4);
            summary_dense_native_worker.then(|| "summary-dense semantic worker islands".to_string())
        }
        r2sym::DecompilePlan::NativeSummaryIslands { reason } => {
            if !capability.skipped_large_cfg && capability.primary_summary_island_count < 16 {
                return None;
            }
            if capability.summary_conflicted || capability.assumption_conflicted {
                Some(preferred_semantic_worker_reason(cfg_summary))
            } else {
                Some(reason.clone())
            }
        }
        r2sym::DecompilePlan::NativeLinear { reason } => {
            if dense_summary_only_memory_worker {
                return Some("dense summary-only memory worker".to_string());
            }
            let summary_dense_native_worker = capability.primary_summary_island_count >= 16
                && (cfg_summary.loop_count > 0
                    || cfg_summary.back_edge_count > 0
                    || capability.actionable_region_count >= 4);
            if summary_dense_native_worker {
                return Some("summary-dense semantic worker islands".to_string());
            }
            let high_risk = cfg_guard_reason_from_summary(cfg_summary).is_some()
                || capability.primary_summary_island_count >= 8
                || large_bounded_memory_worker;
            high_risk.then(|| reason.clone())
        }
        _ => None,
    }
}

#[cfg(test)]
pub(crate) fn preferred_semantic_structuring_reason(
    func_name: &str,
    function_facts: &FunctionFacts,
    cfg_summary: &CFGRiskSummary,
) -> Option<String> {
    let capability = decompile_capability(function_facts);
    if !crate::is_autogenerated_function_name(func_name) {
        return None;
    }
    if !capability
        .plan
        .as_ref()
        .is_some_and(r2sym::DecompilePlan::allows_native_structuring)
    {
        return None;
    }
    if !capability.skipped_large_cfg || !capability.has_native_regions {
        return None;
    }
    if capability.actionable_region_count == 0
        || capability.assumption_conflicted
        || capability.summary_conflicted
        || !capability.ambiguous_targets.is_empty()
    {
        return None;
    }
    Some(preferred_semantic_worker_reason(cfg_summary))
}

#[cfg(test)]
pub(crate) fn preferred_semantic_worker_reason(cfg_summary: &CFGRiskSummary) -> String {
    cfg_guard_reason_from_summary(cfg_summary)
        .unwrap_or_else(|| "semantic worker islands".to_string())
}

#[cfg(test)]
pub fn cfg_guard_reason_from_summary(summary: &CFGRiskSummary) -> Option<String> {
    if summary.loop_count > 8 || summary.back_edge_count > 16 {
        return Some(format!(
            "complex loop graph (loops={}, back_edges={})",
            summary.loop_count, summary.back_edge_count
        ));
    }

    if summary.loop_count > 0 && summary.block_count >= 32 && summary.max_switch_cases >= 32 {
        return Some(format!(
            "dense switch in looped CFG (blocks={}, loops={}, max_switch_cases={})",
            summary.block_count, summary.loop_count, summary.max_switch_cases
        ));
    }

    if summary.loop_count > 4 && summary.block_count >= 96 && summary.max_switch_cases >= 32 {
        return Some(format!(
            "large dense switch in looped CFG (blocks={}, loops={}, max_switch_cases={})",
            summary.block_count, summary.loop_count, summary.max_switch_cases
        ));
    }

    None
}

#[cfg(test)]
pub fn cfg_guard_reason(blocks: &[R2ILBlock]) -> Option<String> {
    let ssa_func = SSAFunction::from_blocks_raw_no_arch(blocks)?;
    cfg_guard_reason_from_summary(&ssa_func.cfg_risk_summary())
}

pub fn block_guard_fallback_comment(func_name: &str, blocks: usize, max_blocks: usize) -> String {
    format!(
        "/* r2dec budget: skipped decompilation for {} ({} blocks > limit {}). */",
        func_name, blocks, max_blocks
    )
}

pub fn artifact_guard_fallback_comment(func_name: &str, reason: &str) -> String {
    format!(
        "/* r2dec fallback: skipped decompilation for {} ({}) */",
        func_name, reason
    )
}

#[cfg(test)]
pub fn semantic_route_plan(
    func_name: &str,
    function_facts: &FunctionFacts,
    cfg_summary: &CFGRiskSummary,
) -> SemanticRoutePlan {
    if let Some(reason) = preferred_vm_summary_reason(function_facts) {
        return SemanticRoutePlan::VmSummary { reason };
    }
    if let Some(comment) = preferred_semantic_fallback_comment(func_name, function_facts) {
        return SemanticRoutePlan::FallbackComment { comment };
    }
    if let Some(reason) = preferred_semantic_summary_islands_reason(function_facts, cfg_summary) {
        return SemanticRoutePlan::SummaryIslands { reason };
    }
    if let Some(reason) =
        preferred_semantic_structuring_reason(func_name, function_facts, cfg_summary)
    {
        return SemanticRoutePlan::StructuredWorker { reason };
    }
    if let Some(reason) =
        preferred_semantic_linearization_reason(func_name, function_facts, cfg_summary)
    {
        return SemanticRoutePlan::LinearWorker { reason };
    }
    if let Some(route) = function_facts
        .semantic_artifact()
        .and_then(semantic_route_from_artifact_plan)
    {
        return route;
    }
    SemanticRoutePlan::Standard
}

#[cfg(test)]
pub fn detached_semantic_route_plan(
    func_name: &str,
    blocks: &[R2ILBlock],
    function_facts: &FunctionFacts,
) -> Option<SemanticRoutePlan> {
    let ssa_func = SSAFunction::from_blocks_raw_no_arch(blocks)?;
    Some(semantic_route_plan(
        func_name,
        function_facts,
        &ssa_func.cfg_risk_summary(),
    ))
}

#[cfg(test)]
pub fn detached_semantic_linearization_reason(
    func_name: &str,
    blocks: &[R2ILBlock],
    function_facts: &FunctionFacts,
) -> Option<String> {
    match detached_semantic_route_plan(func_name, blocks, function_facts)? {
        SemanticRoutePlan::LinearWorker { reason }
        | SemanticRoutePlan::SummaryIslands { reason } => Some(reason),
        _ => None,
    }
}
