mod artifact;
mod claims;
mod classify;
mod compiler;
pub(crate) mod facts;
pub(crate) mod native_worker;
mod plan;
mod region;
mod vm;

pub use artifact::{
    ResidualReason, SEMANTIC_ARTIFACT_SCHEMA_VERSION, SemanticArtifact, SemanticArtifactBody,
    SemanticArtifactReport, SemanticConfidence, SemanticEvidence, SemanticEvidenceAmbiguity,
    SemanticEvidenceCoverage, SemanticEvidenceProvenance, SemanticEvidenceReason,
    SemanticEvidenceSoundness, SliceClass,
};
pub use claims::{
    SEMANTIC_CLAIM_SCHEMA_VERSION, SemanticClaim, SemanticClaimKind, SemanticClaimSource,
    SemanticClaimSummary, SemanticTypeSeedKind, SummaryRoleCertificate, SummaryRouteCertificate,
    SummaryRouteCertificateKind,
};
pub use compiler::{
    compile_function_semantics, compile_native_worker_summary_artifact, compile_semantic_artifact,
    compile_semantic_artifact_default,
    compile_summary_dense_worker_artifact_from_interproc_summary,
};
pub use facts::{SymbolicReachabilityStatus, augment_semantic_artifact_with_interproc_summary};
pub use native_worker::{
    NativeWorkerSummaryApplicability, NativeWorkerSummaryApplicabilitySource,
    NativeWorkerSummaryRouteKind, NativeWorkerSummaryRoutePolicy,
    function_semantic_summary_seed_for_name, function_semantic_summary_seed_for_name_with_linkage,
    has_program_orchestrator_summary_family, is_anonymous_semantic_route_name,
    is_autogenerated_semantic_function_name, native_worker_summary_applicability_for_summary,
    native_worker_summary_route_policy_for_summary, normalize_native_worker_role_name,
    semantic_summary_has_modeled_evidence, semantic_summary_has_runtime_copy_role,
};
pub use plan::{
    ArtifactBuildPlan, DecompilePlan, QueryGuidanceMode, QueryPlan, TargetQueryExecutionRoute,
    TargetQueryPlan, TargetQueryRoutePlan, TypePlan,
};
pub use region::{
    ArtifactGranularity, ControlFact, ExecutionModel, Judged, MemoryFact, NativeArtifactBody,
    NativeFunctionSummary, NativeLoopSummary, NativeMemoryAccessKind, NativeMemoryAccessSummary,
    NativeParserKind, NativeParserReturnPredicate, NativeParserReturnPredicateKind,
    NativeParserSummary, NativeReductionSummary, NativeRegionSummary, NativeTableWalkSummary,
    NativeWorkerByteTransform, NativeWorkerFold, NativeWorkerFoldOperation,
    NativeWorkerLoopSummary, NativeWorkerPredicate, NativeWorkerRoleIdentity,
    NativeWorkerRoleSource, NativeWorkerSummary, NativeWorkerSummaryKind, NativeWorkerTerminator,
    RefinementStage, RegionKey, SemanticArtifactDiagnostics, SemanticPredicate, SemanticRegion,
    SemanticTargetConditionSource, TargetFact, VmArtifactBody,
};
pub use vm::{
    InterpreterDispatchSummary, InterpreterKind, VmBinaryOp, VmGuardCondition, VmGuardedExit,
    VmMemoryCondition, VmMemoryRegionRef, VmStateUpdate, VmStepSummary, VmTransferArm, VmUnaryOp,
    VmValueExpr, has_strong_vm_evidence, strong_vm_step_summary,
};
