[package]
name = "r2sleigh-lift"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Sleigh to r2il translator"

[dependencies]
r2il = { path = "../r2il" }
libsla.workspace = true
thiserror.workspace = true

[dev-dependencies]
sleigh-config = { workspace = true, features = ["AARCH64"] }
