use std::collections::HashSet;

use r2ssa::{ObjectId, ObjectKind, SSAOp, SSAVar};
use r2types::{
    ExternalStackBase, ExternalStackSlotRole, ExternalStackSlotSpec, StackSlotKey, VisibleBinding,
    VisibleBindingKind,
};

use crate::analysis::prepared_semantic::StackAliasView;
use crate::analysis::utils;

/// Whether this spelling names the value a register was entered with.
///
/// Version zero reaches here spelled both ways: `display_name` drops the suffix
/// for it, while the copy-source route keeps it and writes `x30_0`. Only a
/// suffix naming a later version means the register was written since entry.
fn is_entry_value_spelling(display_name: &str) -> bool {
    match display_name.rsplit_once('_') {
        Some((_, version))
            if !version.is_empty() && version.chars().all(|c| c.is_ascii_digit()) =>
        {
            version.parse::<u32>().is_ok_and(|version| version == 0)
        }
        _ => true,
    }
}
use crate::ast::{BinaryOp, CExpr};

use super::context::FoldingContext;
use super::op_lower::is_generic_arg_name;
use super::{MAX_STACK_ALIAS_DEPTH, MAX_STACK_OFFSET_DEPTH};

/// Threshold for detecting 64-bit negative values stored as unsigned.
/// Values above this are likely negative offsets (within ~65536 of u64::MAX).
/// This handles cases like stack offsets: 0xffffffffffffffb8 represents -72.
const LIKELY_NEGATIVE_THRESHOLD: u64 = 0xffffffffffff0000;

impl<'a> FoldingContext<'a> {
    fn preferred_prepared_stack_alias_name(&self, alias: &StackAliasView) -> Option<String> {
        let visible = alias.visible_name.trim();
        alias
            .arg_alias
            .as_ref()
            .filter(|arg_alias| {
                !arg_alias.is_empty()
                    && (visible.is_empty()
                        || visible.ends_with("_home")
                        || visible.starts_with("var_")
                        || visible.starts_with("local_")
                        || visible.starts_with("stack_")
                        || visible.starts_with("arg_"))
            })
            .cloned()
            .or_else(|| (!visible.is_empty()).then(|| visible.to_string()))
            .or_else(|| alias.arg_alias.clone())
    }

    fn prepared_stack_alias_view(&self) -> Option<&crate::analysis::PreparedSemanticView> {
        self.prepared_semantic_view()
    }

    pub(super) fn prepared_stack_offset_for_var(&self, var: &SSAVar) -> Option<i64> {
        let objects = self.prepared_objects()?;
        let object = self
            .inputs
            .prepared_ssa?
            .object_for_var(var, r2il::SpaceId::Ram)
            .or_else(|| {
                self.prepared_canonical_value_root(var).and_then(|root| {
                    self.inputs
                        .prepared_ssa?
                        .object_for_var(&root, r2il::SpaceId::Ram)
                })
            })?;
        let fact = objects.object(object)?;
        match fact.kind {
            ObjectKind::StackSlot { offset, .. } | ObjectKind::FrameObject { offset, .. } => {
                Some(offset)
            }
            _ => None,
        }
    }

    fn is_visible_external_stack_name_role(role: ExternalStackSlotRole) -> bool {
        matches!(
            role,
            ExternalStackSlotRole::Local
                | ExternalStackSlotRole::StackArg
                | ExternalStackSlotRole::Unknown
        )
    }

    pub(super) fn stack_synthetic_name(offset: i64) -> String {
        if offset < 0 {
            format!("local_{:x}", (-offset) as u64)
        } else {
            format!("stack_{:x}", offset as u64)
        }
    }

    fn autogenerated_stack_name_offset(name: &str) -> Option<i64> {
        if name == "saved_fp" {
            return Some(0);
        }
        if let Some(suffix) = name.strip_prefix("local_") {
            return i64::from_str_radix(suffix, 16).ok().map(|value| -value);
        }
        if let Some(suffix) = name.strip_prefix("stack_") {
            return i64::from_str_radix(suffix, 16).ok();
        }
        if let Some(suffix) = name.strip_prefix("arg_") {
            return i64::from_str_radix(suffix, 16).ok().map(|value| -value);
        }
        name.strip_prefix("var_")
            .and_then(|suffix| suffix.strip_suffix('h'))
            .and_then(|suffix| i64::from_str_radix(suffix, 16).ok())
            .map(|value| -value)
    }

    fn bound_stack_name_offset(&self, name: &str) -> Option<i64> {
        let mut offsets = HashSet::new();
        if let Some(view) = self.prepared_stack_alias_view() {
            offsets.extend(
                view.stack_aliases_by_offset
                    .iter()
                    .filter_map(|(offset, alias)| {
                        alias
                            .visible_name
                            .eq_ignore_ascii_case(name)
                            .then_some(*offset)
                    }),
            );
        }
        offsets.extend(self.inputs.visible_bindings.iter().filter_map(|binding| {
            if !binding.name.eq_ignore_ascii_case(name) {
                return None;
            }
            binding.stack_slot.as_ref().map(|slot| match slot.base {
                ExternalStackBase::FramePointer => -slot.offset,
                _ => slot.offset,
            })
        }));
        offsets.extend(
            self.inputs
                .stack_slots
                .iter()
                .filter_map(|(slot_key, slot)| {
                    if !slot.name.eq_ignore_ascii_case(name) {
                        return None;
                    }
                    Some(match slot_key.base {
                        ExternalStackBase::FramePointer => -slot_key.offset,
                        _ => slot_key.offset,
                    })
                }),
        );
        offsets.extend(
            self.stack_vars_map()
                .iter()
                .filter_map(|(offset, candidate)| {
                    candidate.eq_ignore_ascii_case(name).then_some(*offset)
                }),
        );
        (offsets.len() == 1).then(|| *offsets.iter().next().unwrap())
    }

    fn stack_slot_matches_offset(slot: &StackSlotKey, offset: i64) -> bool {
        if slot.offset == offset {
            return true;
        }
        matches!(slot.base, ExternalStackBase::FramePointer) && -slot.offset == offset
    }

    fn has_typed_stack_slot_for_offset(&self, offset: i64) -> bool {
        self.inputs
            .stack_slots
            .keys()
            .any(|slot_key| Self::stack_slot_matches_offset(slot_key, offset))
            || self.stack_slots().any(|slot| slot.offset == offset)
    }

    fn visible_stack_binding_for_offset(&self, offset: i64) -> Option<&VisibleBinding> {
        self.inputs.visible_bindings.iter().find(|binding| {
            binding
                .stack_slot
                .as_ref()
                .is_some_and(|slot| Self::stack_slot_matches_offset(slot, offset))
        })
    }

    fn certified_stack_owner_candidate_names(&self, offset: i64) -> Vec<String> {
        let prepared_alias = self
            .prepared_stack_alias_view()
            .and_then(|view| view.stack_alias_for_offset(offset))
            .and_then(|alias| self.preferred_prepared_stack_alias_name(alias));
        let mut names: Vec<String> = prepared_alias.into_iter().collect();
        names.extend(
            self.inputs
                .visible_bindings
                .iter()
                .filter(move |binding| {
                    matches!(
                        binding.kind,
                        VisibleBindingKind::Param
                            | VisibleBindingKind::Local
                            | VisibleBindingKind::StackObject
                    ) && binding
                        .stack_slot
                        .as_ref()
                        .is_some_and(|slot| Self::stack_slot_matches_offset(slot, offset))
                })
                .map(|binding| binding.name.trim().to_string()),
        );
        names.extend(
            self.inputs
                .stack_slots
                .iter()
                .filter(move |(slot_key, slot)| {
                    matches!(
                        slot.role,
                        ExternalStackSlotRole::Local | ExternalStackSlotRole::StackArg
                    ) && Self::stack_slot_matches_offset(slot_key, offset)
                })
                .map(|(_, slot)| slot.name.trim().to_string()),
        );
        names
    }

    pub(super) fn certified_stack_var_name_for_object_offset(
        &self,
        object: ObjectId,
        offset: i64,
    ) -> Option<String> {
        let function_facts = self.inputs.function_facts;
        self.certified_stack_owner_candidate_names(offset)
            .into_iter()
            .filter(|name| {
                !name.is_empty()
                    && !self.is_reserved_param_alias_name(name)
                    && !super::op_lower::is_generic_stack_placeholder_alias(name)
            })
            .find(|name| {
                function_facts
                    .authorized_stack_slot_owner_render(object, offset, name)
                    .or_else(|| {
                        function_facts
                            .authorized_recovered_stack_slot_owner_render(object, offset, name)
                    })
                    .is_some()
            })
    }

    pub(super) fn is_reserved_param_alias_name(&self, name: &str) -> bool {
        let lower = name.to_ascii_lowercase();
        self.inputs
            .param_register_aliases
            .values()
            .any(|alias| alias.eq_ignore_ascii_case(&lower))
    }

    /// Try to extract a stack offset from a variable name or its definition.
    pub(crate) fn extract_stack_offset_from_var(&self, var: &SSAVar) -> Option<i64> {
        if let Some(offset) = self
            .prepared_stack_alias_view()
            .and_then(|view| view.stack_offset_for_var(var))
        {
            return Some(offset);
        }
        if let Some(offset) = self.prepared_stack_offset_for_var(var) {
            return Some(offset);
        }

        let name_lower = var.name.to_lowercase();

        // Direct fp/sp reference
        if self.inputs.arch.is_stack_base_name(&name_lower) {
            return Some(0);
        }

        if let Some(slot) = self.stack_slot_provenance_for_var(var) {
            return Some(slot.offset);
        }

        // Check if this variable was defined as fp/sp + offset
        if let Some(expr) = self.definition_for_name(&var.display_name()) {
            return self.extract_offset_from_expr(expr);
        }

        None
    }

    /// Extract stack offset from an expression like (rbp + -0x48).
    pub(super) fn extract_offset_from_expr(&self, expr: &CExpr) -> Option<i64> {
        self.extract_offset_from_expr_with_depth(expr, 0)
    }

    pub(super) fn extract_offset_from_expr_with_depth(
        &self,
        expr: &CExpr,
        depth: u32,
    ) -> Option<i64> {
        if depth > MAX_STACK_OFFSET_DEPTH {
            return None;
        }

        match expr.unobserved() {
            CExpr::Paren(inner) => self.extract_offset_from_expr_with_depth(inner, depth + 1),
            CExpr::Cast { expr: inner, .. } => {
                self.extract_offset_from_expr_with_depth(inner, depth + 1)
            }
            CExpr::Binary {
                op: BinaryOp::Add,
                left,
                right,
            } => {
                if self.is_stack_base_expr(left) {
                    return self.expr_to_offset(right);
                }
                if self.is_stack_base_expr(right) {
                    return self.expr_to_offset(left);
                }
                None
            }
            CExpr::Binary {
                op: BinaryOp::Sub,
                left,
                right,
            } => {
                if self.is_stack_base_expr(left) {
                    return self.expr_to_offset(right).map(|off| -off);
                }
                None
            }
            CExpr::Var(name) => {
                let name_lower = self.spelling(*name).to_lowercase();
                if self.inputs.arch.is_stack_base_name(&name_lower) {
                    return Some(0);
                }
                // Stack provenance is a property of the raw SSA address chain.
                // Full visible-definition resolution also ranks semantic values,
                // call-result owners, and rendered aliases, which cannot improve
                // an FP/SP-relative offset and may erase the address shape.
                self.lookup_definition_raw(&self.spelling(*name))
                    .and_then(|inner| self.extract_offset_from_expr_with_depth(&inner, depth + 1))
            }
            _ => None,
        }
    }

    pub(super) fn is_stack_base_expr(&self, expr: &CExpr) -> bool {
        match expr.unobserved() {
            CExpr::Var(name) => self
                .inputs
                .arch
                .is_stack_base_name(&self.spelling(*name).to_lowercase()),
            CExpr::Paren(inner) | CExpr::Cast { expr: inner, .. } | CExpr::AddrOf(inner) => {
                self.is_stack_base_expr(inner)
            }
            _ => false,
        }
    }

    /// Convert an expression to an offset value.
    pub(super) fn expr_to_offset(&self, expr: &CExpr) -> Option<i64> {
        match expr.unobserved() {
            CExpr::IntLit(v) => Some(*v),
            CExpr::UIntLit(v) => {
                // Handle negative offsets stored as unsigned
                if *v > LIKELY_NEGATIVE_THRESHOLD {
                    let neg = (!*v).wrapping_add(1);
                    Some(-(neg as i64))
                } else {
                    Some(*v as i64)
                }
            }
            _ => None,
        }
    }

    pub(super) fn arg_alias_for_register_name(&self, reg_name: &str) -> Option<String> {
        let lower = reg_name.to_ascii_lowercase();
        if let Some(alias) = self.inputs.param_register_aliases.get(&lower) {
            return Some(alias.clone());
        }
        // Width-variant register names (e.g. `rsi` vs alias key `esi`) must
        // resolve through their canonical argument register before giving up.
        for (alias_reg, alias) in self.inputs.param_register_aliases {
            if self
                .canonical_arg_register_name_for_alias(alias_reg)
                .eq_ignore_ascii_case(&lower)
            {
                return Some(alias.clone());
            }
        }

        self.inputs.arch.arg_alias_for_register_name(reg_name)
    }

    pub(super) fn arg_alias_for_rendered_name(&self, name: &str) -> Option<String> {
        let lower = name.to_lowercase();
        // A carrier holds whatever the loop last put there, so it is never an
        // argument, even though it is spelled bare like an entry value is.
        if self.is_carrier_rendered_name(&lower) {
            return None;
        }
        if let Some((base, version)) = lower.rsplit_once('_') {
            if version != "0" {
                return None;
            }
            return self.arg_alias_for_register_name(base);
        }
        self.arg_alias_for_register_name(&lower)
    }

    /// Whether a copy restates a carrier update the block has already rendered.
    ///
    /// Materialising a merge replaces it with a copy on every predecessor edge,
    /// so a loop carries its update back to the header as `X8_2 = X8_3`. Once the
    /// alias map covers what materialisation introduced, both sides are spelled
    /// by the carrier's one name and the copy says `x8 = x8`, which the statement
    /// that computed the update has already said.
    ///
    /// The edge into the loop is the same kind of copy and must be kept, because
    /// nothing else introduces the carrier there. The two are told apart by
    /// whether the source is an entry value: a version-0 source is the value the
    /// function was called with and has no defining statement of its own, so the
    /// copy is the only place the carrier is given it.
    pub(super) fn is_carrier_self_copy(&self, dst: &SSAVar, src: &SSAVar) -> bool {
        if src.version == 0 {
            return false;
        }
        let (Some(dst_carrier), Some(src_carrier)) = (
            self.carrier_aliases.get(&dst.display_name()),
            self.carrier_aliases.get(&src.display_name()),
        ) else {
            return false;
        };
        dst_carrier == src_carrier
    }

    pub(super) fn is_entry_arg_alias_copy(&self, dst: &SSAVar, src: &SSAVar) -> bool {
        if src.version != 0 {
            return false;
        }

        let Some(src_alias) = self.arg_alias_for_register_name(&src.name) else {
            return false;
        };
        let dst_name = self.var_name(dst);
        is_generic_arg_name(&dst_name) && dst_name.eq_ignore_ascii_case(&src_alias)
    }

    pub(super) fn is_entry_arg_alias_store(&self, addr: &SSAVar, val: &SSAVar) -> bool {
        let entry_arg_alias = utils::arg_alias_for_store_source(
            val,
            |name| self.copy_source_of(name),
            self.var_aliases_map(),
            self.inputs.param_register_aliases,
        )
        .or_else(|| {
            self.lookup_definition_raw(&val.display_name())
                .and_then(|expr| self.arg_alias_for_expr(&expr))
        });
        if entry_arg_alias.is_none() {
            return false;
        }
        self.stack_slot_provenance_for_var(addr)
            .map(|slot| slot.offset)
            .or_else(|| self.extract_stack_offset_from_var(addr))
            .is_some()
    }

    pub(super) fn arg_alias_for_expr(&self, expr: &CExpr) -> Option<String> {
        match expr.unobserved() {
            CExpr::Var(name) => self.arg_alias_for_rendered_name(&self.spelling(*name)),
            CExpr::Paren(inner) => self.arg_alias_for_expr(inner),
            CExpr::Cast { expr: inner, .. } => self.arg_alias_for_expr(inner),
            _ => None,
        }
    }

    fn prepared_transparent_source_var(&self, var: &SSAVar) -> Option<SSAVar> {
        self.prepared_transparent_source_var_inner(var, 0, &mut HashSet::new())
    }

    fn prepared_transparent_source_var_inner(
        &self,
        var: &SSAVar,
        depth: u32,
        visited: &mut HashSet<r2ssa::ValueId>,
    ) -> Option<SSAVar> {
        if depth > MAX_STACK_ALIAS_DEPTH {
            return None;
        }
        if var.version == 0 && var.is_register() {
            return Some(var.clone());
        }
        let prepared = self.inputs.prepared_ssa?;
        let value = self.prepared_value_id_for_var(var)?;
        if !visited.insert(value) {
            return None;
        }
        let result = (|| {
            let inst_id = prepared.graph().def_inst(value)?;
            let inst = prepared.graph().inst(inst_id)?;
            let r2ssa::InstPayload::Op(op) = &inst.payload else {
                return None;
            };
            let src = match op {
                SSAOp::Copy { src, .. }
                | SSAOp::New { src, .. }
                | SSAOp::Cast { src, .. }
                | SSAOp::Subpiece { src, .. }
                | SSAOp::IntZExt { src, .. }
                | SSAOp::IntSExt { src, .. }
                | SSAOp::Trunc { src, .. } => src,
                _ => return None,
            };
            self.prepared_transparent_source_var_inner(src, depth + 1, visited)
        })();
        visited.remove(&value);
        result
    }

    /// Check if an address expression is a stack access and return the variable name.
    pub fn simplify_stack_access(&self, addr_expr: &CExpr) -> Option<String> {
        match addr_expr.unobserved() {
            CExpr::Paren(inner) => return self.simplify_stack_access(inner),
            CExpr::Cast { expr: inner, .. } => return self.simplify_stack_access(inner),
            CExpr::AddrOf(inner) => return self.simplify_stack_access(inner),
            CExpr::Var(name) => {
                if let Some(stripped) = self.spelling(*name).strip_prefix('&') {
                    return Some(stripped.to_string());
                }
            }
            _ => {}
        }

        if let Some(offset) = self.extract_offset_from_expr(addr_expr) {
            return self.resolve_stack_var(offset);
        }
        None
    }

    pub(super) fn resolve_stack_alias_from_addr_expr(
        &self,
        expr: &CExpr,
        depth: u32,
    ) -> Option<String> {
        if depth > MAX_STACK_ALIAS_DEPTH {
            return None;
        }

        if let Some(alias) = self.simplify_stack_access(expr) {
            return Some(alias);
        }

        match expr.unobserved() {
            CExpr::Var(name) => {
                if let Some(stripped) = self.spelling(*name).strip_prefix('&') {
                    return Some(stripped.to_string());
                }
                if let Some(offset) = self.bound_stack_name_offset(&self.spelling(*name)) {
                    return self
                        .resolve_stack_var(offset)
                        .or_else(|| Some(self.spelling(*name).to_string()));
                }
                let parsed_offset = Self::autogenerated_stack_name_offset(&self.spelling(*name));
                if let Some(offset) = parsed_offset
                    && let Some(alias) = self.resolve_stack_var(offset)
                {
                    return Some(alias);
                }
                self.lookup_definition(&self.spelling(*name))
                    .and_then(|inner| self.resolve_stack_alias_from_addr_expr(&inner, depth + 1))
            }
            CExpr::Paren(inner) => self.resolve_stack_alias_from_addr_expr(inner, depth + 1),
            CExpr::Cast { expr: inner, .. } => {
                self.resolve_stack_alias_from_addr_expr(inner, depth + 1)
            }
            CExpr::AddrOf(inner) => self.resolve_stack_alias_from_addr_expr(inner, depth + 1),
            CExpr::Deref(inner) => self.resolve_stack_alias_from_addr_expr(inner, depth + 1),
            _ => None,
        }
    }
    pub(crate) fn stack_var_for_addr_var(&self, addr: &SSAVar) -> Option<String> {
        if let Some(expr) = self
            .prepared_stack_alias_view()
            .and_then(|view| view.owner_expr_for_var(addr))
        {
            match expr.unobserved() {
                CExpr::Var(name) => return Some(self.spelling(*name).to_string()),
                CExpr::AddrOf(inner) => {
                    if let CExpr::Var(name) = inner.unobserved() {
                        return Some(self.spelling(*name).to_string());
                    }
                }
                _ => {}
            }
        }
        let addr_key = addr.display_name();
        if let Some(alias) =
            self.resolve_stack_alias_from_addr_expr(&self.name_ref(&addr_key.clone()), 0)
        {
            return Some(alias);
        }
        if let Some(alias) =
            self.resolve_stack_alias_from_addr_expr(&self.name_ref(&self.var_name(addr)), 0)
        {
            return Some(alias);
        }
        self.extract_stack_offset_from_var(addr)
            .and_then(|offset| self.resolve_stack_var(offset))
    }

    pub(super) fn external_stack_name_for_offset(&self, offset: i64) -> Option<String> {
        if let Some(alias_name) = self
            .prepared_stack_alias_view()
            .and_then(|view| view.stack_alias_for_offset(offset))
            .and_then(|alias| self.preferred_prepared_stack_alias_name(alias))
        {
            return Some(alias_name);
        }
        if let Some(binding) = self.visible_stack_binding_for_offset(offset) {
            match binding.kind {
                VisibleBindingKind::Param
                | VisibleBindingKind::Local
                | VisibleBindingKind::StackObject
                | VisibleBindingKind::Unknown => {
                    if !binding.name.is_empty() && !self.is_reserved_param_alias_name(&binding.name)
                    {
                        return Some(binding.name.clone());
                    }
                }
                VisibleBindingKind::HiddenHome => {
                    if let Some(alias) = self.visible_param_home_alias_for_binding(binding) {
                        return Some(alias);
                    }
                }
                VisibleBindingKind::HiddenSaved => {}
            }
        }

        for (slot_key, slot_spec) in self.inputs.stack_slots {
            if !Self::stack_slot_matches_offset(slot_key, offset) {
                continue;
            }
            if let Some(alias) = self.visible_param_home_alias_for_slot(slot_spec) {
                return Some(alias);
            }
            if !slot_spec.name.is_empty()
                && Self::is_visible_external_stack_name_role(slot_spec.role)
                && !self.is_reserved_param_alias_name(&slot_spec.name)
            {
                return Some(slot_spec.name.clone());
            }
        }

        None
    }

    pub(super) fn param_home_alias_for_stack_offset(&self, offset: i64) -> Option<String> {
        if let Some(alias_name) = self
            .prepared_stack_alias_view()
            .and_then(|view| view.stack_alias_for_offset(offset))
            .filter(|alias| matches!(alias.binding_kind, Some(VisibleBindingKind::HiddenHome)))
            .and_then(|alias| alias.arg_alias.as_deref())
            .map(str::trim)
            .filter(|alias| self.is_valid_param_home_alias(alias))
        {
            return Some(alias_name.to_string());
        }

        if let Some(binding) = self.visible_stack_binding_for_offset(offset)
            && matches!(binding.kind, VisibleBindingKind::HiddenHome)
            && let Some(alias) = self.visible_param_home_alias_for_binding(binding)
            && self.is_valid_param_home_alias(&alias)
        {
            return Some(alias);
        }

        self.inputs
            .stack_slots
            .iter()
            .find(|(slot_key, slot)| {
                matches!(slot.role, ExternalStackSlotRole::ParamHome)
                    && Self::stack_slot_matches_offset(slot_key, offset)
            })
            .and_then(|(_, slot)| self.visible_param_home_alias_for_slot(slot))
            .filter(|alias| self.is_valid_param_home_alias(alias))
    }

    fn visible_param_home_alias_for_binding(&self, binding: &VisibleBinding) -> Option<String> {
        if !matches!(binding.kind, VisibleBindingKind::HiddenHome) {
            return None;
        }

        if let Some(param_name) = binding
            .param_index
            .and_then(|idx| {
                self.inputs.visible_bindings.iter().find(|candidate| {
                    matches!(candidate.kind, VisibleBindingKind::Param)
                        && candidate.param_index == Some(idx)
                })
            })
            .map(|binding| binding.name.trim())
            .filter(|name| {
                !name.is_empty()
                    && !self.is_reserved_param_alias_name(name)
                    && !super::op_lower::is_generic_stack_placeholder_alias(name)
                    && self.canonicalize_stack_name(name).is_none()
                    && !name.eq_ignore_ascii_case("local")
            })
        {
            return Some(param_name.to_string());
        }

        binding
            .source_reg
            .as_deref()
            .and_then(|reg| self.arg_alias_for_register_name(reg))
            .or_else(|| {
                let binding_name = binding.name.trim();
                (!binding_name.is_empty()
                    && !self.is_reserved_param_alias_name(binding_name)
                    && !super::op_lower::is_generic_stack_placeholder_alias(binding_name)
                    && self.canonicalize_stack_name(binding_name).is_none()
                    && !binding_name.eq_ignore_ascii_case("local"))
                .then(|| binding_name.to_string())
            })
    }

    fn visible_param_home_alias_for_slot(&self, slot: &ExternalStackSlotSpec) -> Option<String> {
        if !matches!(slot.role, ExternalStackSlotRole::ParamHome) {
            return None;
        }

        if let Some(param_name) = slot.param_name.as_deref()
            && !param_name.trim().is_empty()
        {
            return Some(param_name.to_string());
        }

        slot.source_reg
            .as_deref()
            .and_then(|reg| self.arg_alias_for_register_name(reg))
    }

    fn is_valid_param_home_alias(&self, alias: &str) -> bool {
        let alias = alias.trim();
        !alias.is_empty()
            && !super::op_lower::is_generic_stack_placeholder_alias(alias)
            && !self.is_transient_visible_name(alias)
            && !self.is_low_signal_visible_name(alias)
    }

    pub(super) fn canonicalize_stack_name(&self, name: &str) -> Option<String> {
        let offset = self
            .bound_stack_name_offset(name)
            .or_else(|| Self::autogenerated_stack_name_offset(name))?;

        self.external_stack_name_for_offset(offset)
    }

    /// Resolve a stack variable name by signed stack offset.
    /// Whether an address a frame operation loads from or stores to is a stack
    /// slot.
    ///
    /// A prologue push and an epilogue pop reach the stack through a temporary,
    /// so a temporary had to be accepted here. Accepting every temporary meant
    /// accepting `ldr x19, [x19, 0x38]` -- a field load into a callee-saved
    /// register -- as an epilogue restore, and deleting it while its uses
    /// stayed. What makes an address part of the frame is where it points, so
    /// that is what is asked.
    pub(super) fn addr_is_stack_slot(&self, addr: &SSAVar) -> bool {
        utils::is_temporary_name(&addr.name) && self.stack_slot_offset_for_var(addr).is_some()
    }

    pub fn resolve_stack_var(&self, offset: i64) -> Option<String> {
        if let Some(alias_name) = self
            .prepared_stack_alias_view()
            .and_then(|view| view.stack_alias_for_offset(offset))
            .and_then(|alias| self.preferred_prepared_stack_alias_name(alias))
        {
            return Some(alias_name);
        }
        let external_name = self.external_stack_name_for_offset(offset);
        let resolved = self
            .stack_vars_map()
            .get(&offset)
            .cloned()
            .map(|name| self.canonicalize_stack_name(&name).unwrap_or(name))
            .map(|name| {
                if (name == "saved_fp"
                    || name.starts_with("local_")
                    || name.starts_with("stack_")
                    || name.starts_with("arg_"))
                    && external_name.is_some()
                {
                    external_name.clone().unwrap()
                } else {
                    name
                }
            })
            .or_else(|| external_name.clone())
            .or_else(|| {
                self.has_typed_stack_slot_for_offset(offset)
                    .then(|| Self::stack_synthetic_name(offset))
            });
        resolved.and_then(|name| {
            if self.is_reserved_param_alias_name(&name) {
                self.has_typed_stack_slot_for_offset(offset)
                    .then(|| Self::stack_synthetic_name(offset))
            } else {
                Some(name)
            }
        })
    }

    pub(super) fn rewrite_stack_expr(&self, expr: CExpr) -> CExpr {
        if let CExpr::Observed { id, expr } = expr {
            return CExpr::observed(id, self.rewrite_stack_expr(*expr));
        }
        let rewritten = expr.map_children(&mut |child| self.rewrite_stack_expr(child));

        if let CExpr::Var(name) = &rewritten
            && let Some(alias) = self.resolve_stack_alias_from_addr_expr(&CExpr::Var(*name), 0)
            && *alias != *self.spelling(*name)
            && !super::op_lower::is_generic_stack_placeholder_alias(&alias)
        {
            return self.name_ref(&alias);
        }

        if matches!(
            rewritten.unobserved(),
            CExpr::Binary {
                op: BinaryOp::Add | BinaryOp::Sub,
                ..
            } | CExpr::Paren(_)
                | CExpr::Cast { .. }
        ) && let Some(alias) = self.resolve_stack_alias_from_addr_expr(&rewritten, 0)
            && !super::op_lower::is_generic_stack_placeholder_alias(&alias)
        {
            return crate::ast::carry_expr_render_observations(&rewritten, self.name_ref(&alias));
        }

        match rewritten {
            CExpr::Deref(inner) => {
                if let Some(alias) = self.resolve_stack_alias_from_addr_expr(&inner, 0)
                    && !super::op_lower::is_generic_stack_placeholder_alias(&alias)
                {
                    return crate::ast::carry_expr_render_observations(
                        &inner,
                        self.name_ref(&alias),
                    );
                }
                if let Some(var_name) = self.extract_known_stack_var_name(&inner) {
                    return crate::ast::carry_expr_render_observations(
                        &inner,
                        self.name_ref(&var_name),
                    );
                }
                CExpr::Deref(inner)
            }
            other => other,
        }
    }

    pub(super) fn extract_known_stack_var_name(&self, expr: &CExpr) -> Option<String> {
        match expr.unobserved() {
            CExpr::Var(name) => {
                if self
                    .stack_vars_map()
                    .values()
                    .any(|candidate| candidate.as_str() == &*self.spelling(*name))
                {
                    Some(self.spelling(*name).to_string())
                } else {
                    None
                }
            }
            CExpr::Paren(inner) | CExpr::Cast { expr: inner, .. } => {
                self.extract_known_stack_var_name(inner)
            }
            _ => None,
        }
    }

    pub(super) fn is_zeroing_expr(&self, expr: &CExpr) -> bool {
        match expr.unobserved() {
            CExpr::Binary {
                op: BinaryOp::BitXor | BinaryOp::Sub,
                left,
                right,
            } => left.transparently_eq(right),
            _ => false,
        }
    }

    /// Check if an operation is part of stack frame setup/teardown (prologue/epilogue).
    pub fn is_stack_frame_op(&self, op: &SSAOp) -> bool {
        if !self.hide_stack_frame {
            return false;
        }

        match op {
            // push rbp: Store to (rsp - 8) where value is rbp
            SSAOp::Store {
                space: r2il::SpaceId::Ram,
                addr,
                val,
            } => {
                let addr_name = addr.name.to_lowercase();
                let val_name = val.name.to_lowercase();
                let addr_is_sp = self.inputs.arch.is_stack_pointer_name(&addr_name);
                // Store of fp to stack (push fp)
                if self.inputs.arch.is_frame_pointer_name(&val_name)
                    && (addr_is_sp || addr_name.contains("tmp:"))
                {
                    return true;
                }
                // Store return address to stack
                if val_name.contains("rip") || val_name.contains("eip") {
                    return true;
                }
                // Store constant to RSP-derived address (pre-call return address push)
                if val.is_const() && (addr_is_sp || self.addr_is_stack_slot(addr)) {
                    // Check if this constant was consumed by call-arg analysis
                    let val_key = val.display_name();
                    if self.consumed_by_call_set().contains(&val_key) {
                        return true;
                    }
                }
                // Store callee-saved register to stack (prologue push)
                // The P-code often uses temps: Copy tmp:X = RBX; Store [RSP], tmp:X
                // So we need to check both direct and indirect through temps.
                if (addr_is_sp || self.addr_is_stack_slot(addr)) && !val.is_const() {
                    // Direct: val is a callee-saved register, or the entry
                    // value of the frame record. `stp x29, x30, [sp, N]` writes
                    // the second of those, and only the value the function was
                    // entered with is prologue state -- a later value in the
                    // same register is a scratch use and its store is real.
                    if self.inputs.arch.is_callee_saved_name(&val_name)
                        || (self.inputs.arch.is_frame_record_name(&val_name)
                            && is_entry_value_spelling(&val_name))
                    {
                        return true;
                    }
                    // Indirect: val is a temp, trace it back via copy_sources
                    if utils::is_temporary_name(&val.name) {
                        let val_key = val.display_name();
                        if let Some(src_key) =
                            self.render_copy_source_for_name(&val_key).or_else(|| {
                                self.prepared_transparent_source_var(val)
                                    .map(|src| src.display_name())
                            })
                        {
                            let src_lower = src_key.to_lowercase();
                            if self.inputs.arch.is_callee_saved_name(&src_lower)
                                || (self.inputs.arch.is_frame_record_name(&src_lower)
                                    && is_entry_value_spelling(&src_lower))
                            {
                                return true;
                            }
                        }
                    }
                }
                false
            }
            // mov rbp, rsp: Copy from sp to fp
            SSAOp::Copy { dst, src } => {
                let dst_name = dst.name.to_lowercase();
                let src_name = src.name.to_lowercase();
                // mov fp, sp (frame pointer setup)
                if self.inputs.arch.is_frame_pointer_name(&dst_name)
                    && self.inputs.arch.is_stack_pointer_name(&src_name)
                {
                    return true;
                }
                // mov sp, fp (frame pointer teardown)
                if self.inputs.arch.is_stack_pointer_name(&dst_name)
                    && self.inputs.arch.is_frame_pointer_name(&src_name)
                {
                    return true;
                }
                false
            }
            // sub rsp, N: Stack allocation
            SSAOp::IntSub { dst, a, b } => {
                let dst_name = dst.name.to_lowercase();
                let a_name = a.name.to_lowercase();
                // sp = sp - const (stack allocation)
                if self.inputs.arch.is_stack_pointer_name(&dst_name)
                    && self.inputs.arch.is_stack_pointer_name(&a_name)
                    && b.is_const()
                {
                    return true;
                }
                false
            }
            // add rsp, N: Stack deallocation
            SSAOp::IntAdd { dst, a, b } => {
                let dst_name = dst.name.to_lowercase();
                let a_name = a.name.to_lowercase();
                // sp = sp + const (stack deallocation)
                if self.inputs.arch.is_stack_pointer_name(&dst_name)
                    && self.inputs.arch.is_stack_pointer_name(&a_name)
                    && b.is_const()
                {
                    return true;
                }
                // sp = fp + const (leave instruction equivalent)
                if self.inputs.arch.is_stack_pointer_name(&dst_name)
                    && self.inputs.arch.is_frame_pointer_name(&a_name)
                    && b.is_const()
                {
                    return true;
                }
                false
            }
            // pop rbp: Load from stack to fp
            SSAOp::Load {
                dst,
                space: r2il::SpaceId::Ram,
                addr,
            } => {
                let dst_name = dst.name.to_lowercase();
                let addr_name = addr.name.to_lowercase();
                let addr_is_sp = self.inputs.arch.is_stack_pointer_name(&addr_name);
                // Load fp from stack (pop fp)
                if self.inputs.arch.is_frame_pointer_name(&dst_name)
                    && (addr_is_sp || self.addr_is_stack_slot(addr))
                {
                    return true;
                }
                // Load return address (ret)
                if dst_name.contains("rip") || dst_name.contains("eip") {
                    return true;
                }
                // Load callee-saved register from stack (epilogue pop)
                if (addr_is_sp || self.addr_is_stack_slot(addr))
                    && self.inputs.arch.is_callee_saved_name(&dst_name)
                {
                    return true;
                }
                false
            }
            _ => false,
        }
    }
}

#[cfg(test)]
mod observation_transparency_tests {
    use super::*;
    use crate::ast::{CFunction, CStmt, CType, RenderObservationOwner, strip_render_observations};

    fn marked_stack_address(ctx: &FoldingContext<'_>, owner: &mut RenderObservationOwner) -> CExpr {
        let (_, base) = owner.observe_expr(ctx.name_ref("rbp")).unwrap();
        let (_, offset) = owner.observe_expr(CExpr::IntLit(-8)).unwrap();
        let address = CExpr::binary(BinaryOp::Add, CExpr::Paren(Box::new(base)), offset);
        let (_, address) = owner.observe_expr(address).unwrap();
        CExpr::Paren(Box::new(address))
    }

    fn validate_and_strip_expr(expr: CExpr, owner: &RenderObservationOwner) -> CExpr {
        let mut function =
            CFunction::new("observation_test", CType::Void).with_body(vec![CStmt::Expr(expr)]);
        let reachable = strip_render_observations(&mut function, owner.expected_count()).unwrap();
        assert_eq!(reachable.ids().count(), owner.expected_count());
        let CStmt::Expr(expr) = function.body.pop().unwrap() else {
            panic!("test expression changed statement kind");
        };
        expr
    }

    #[test]
    fn nested_observed_frame_pointer_offset_is_semantically_visible() {
        let ctx = FoldingContext::new(64);
        let mut owner = RenderObservationOwner::new();
        let address = marked_stack_address(&ctx, &mut owner);

        assert_eq!(ctx.extract_offset_from_expr(&address), Some(-8));
        let stripped = validate_and_strip_expr(address, &owner);
        assert_eq!(ctx.extract_offset_from_expr(&stripped), Some(-8));
    }

    #[test]
    fn nested_observed_stack_alias_rewrite_moves_each_marker_once() {
        let mut ctx = FoldingContext::new(64);
        ctx.state
            .analysis_ctx
            .stack_info
            .stack_vars
            .insert(-8, "value".to_string());
        let mut owner = RenderObservationOwner::new();
        let address = marked_stack_address(&ctx, &mut owner);
        assert_eq!(ctx.extract_offset_from_expr(&address), Some(-8));
        assert_eq!(ctx.resolve_stack_var(-8), Some("value".to_string()));
        assert_eq!(
            ctx.resolve_stack_alias_from_addr_expr(&address, 0),
            Some("value".to_string())
        );
        let rewritten_address = ctx.rewrite_stack_expr(address.clone());
        assert!(
            rewritten_address.transparently_eq(&ctx.name_ref("value")),
            "unexpected address rewrite: {rewritten_address:?}"
        );
        let rewritten = ctx.rewrite_stack_expr(CExpr::Deref(Box::new(address)));

        assert!(
            rewritten.transparently_eq(&ctx.name_ref("value")),
            "unexpected stack rewrite: {rewritten:?}"
        );
        let stripped = validate_and_strip_expr(rewritten, &owner);
        assert_eq!(stripped, ctx.name_ref("value"));
    }

    #[test]
    fn nested_observed_operands_still_form_zeroing_expression() {
        let ctx = FoldingContext::new(64);
        let mut owner = RenderObservationOwner::new();
        let (_, left) = owner.observe_expr(ctx.name_ref("rax")).unwrap();
        let (_, right) = owner.observe_expr(ctx.name_ref("rax")).unwrap();
        let zeroing = CExpr::binary(BinaryOp::BitXor, left, right);
        let (_, zeroing) = owner.observe_expr(zeroing).unwrap();

        assert!(ctx.is_zeroing_expr(&zeroing));
        let stripped = validate_and_strip_expr(zeroing, &owner);
        assert!(ctx.is_zeroing_expr(&stripped));
    }
}
