use super::*;

impl<'a> FoldingContext<'a> {
    pub(super) fn is_prunable_dead_binding_target(&self, name: &str) -> bool {

        if self.state.return_stack_slots.iter().any(|offset| {
            self.resolve_stack_var(*offset)
                .is_some_and(|candidate| candidate.eq_ignore_ascii_case(name))
        }) {
            return false;
        }
        if self.is_ephemeral_ssa_target(name) {
            return true;
        }
        let lower = name.to_ascii_lowercase();
        lower == "stack"
            || lower.starts_with("value_")
            || self.is_autogenerated_stack_home_name(name)
    }

    pub(super) fn semantic_var_requires_structured_candidate(&self, name: crate::symbol::SymbolId) -> bool {
        let name_id = name;
        let name = &self.spelling(name_id);

        self.semantic_var_requires_structured_candidate_inner(name, &mut HashSet::new())
    }

    fn semantic_var_requires_structured_candidate_inner(
        &self,
        name: &str,
        visited: &mut HashSet<String>,
    ) -> bool {
        if !visited.insert(name.to_string()) {
            return false;
        }

        let direct = match self.lookup_semantic_value(name) {
            Some(crate::analysis::SemanticValue::Address(addr))
            | Some(crate::analysis::SemanticValue::Load { addr, .. }) => {
                addr.index.is_some() || addr.offset_bytes != 0
            }
            Some(crate::analysis::SemanticValue::Scalar(crate::analysis::ScalarValue::Root(
                root,
            ))) => {
                self.semantic_var_requires_structured_candidate_inner(&root.display_name(), visited)
            }
            _ => false,
        };
        if direct {
            return true;
        }

        if let Some(copy_root) = self.render_copy_source_for_name(name)
            && self.semantic_var_requires_structured_candidate_inner(&copy_root, visited)
        {
            return true;
        }

        self.find_ssa_name_for_rendered_alias(name)
            .is_some_and(|ssa_name| {
                ssa_name != name
                    && self.semantic_var_requires_structured_candidate_inner(&ssa_name, visited)
            })
    }

    fn alias_rewrite_keeps_semantics(&self, current: &CExpr, candidate: &CExpr) -> bool {
        if self.expr_contains_generic_stack_alias(candidate)
            || self.is_uninitialized_return_reg(candidate)
        {
            return false;
        }

        match current {
            CExpr::Var(name) if self.semantic_var_requires_structured_candidate(*name) => {
                matches!(
                    candidate,
                    CExpr::Subscript { .. } | CExpr::Member { .. } | CExpr::PtrMember { .. }
                )
            }
            CExpr::Subscript { .. } | CExpr::Member { .. } | CExpr::PtrMember { .. } => {
                matches!(
                    candidate,
                    CExpr::Subscript { .. } | CExpr::Member { .. } | CExpr::PtrMember { .. }
                )
            }
            CExpr::Var(_) => true,
            _ => true,
        }
    }

    fn choose_alias_rewrite(&self, current: CExpr, candidate: CExpr) -> CExpr {
        if self.is_preservable_named_stack_slot_expr(&current)
            && self.is_direct_constish_visible_expr(&candidate, 0)
        {
            return current;
        }
        if let CExpr::Var(name) = &current
            && self.is_autogenerated_stack_home_name(&self.spelling(*name))
            && self.alias_rewrite_keeps_semantics(&current, &candidate)
        {
            return candidate;
        }
        if self.prefers_visible_expr(&current, &candidate)
            && self.alias_rewrite_keeps_semantics(&current, &candidate)
        {
            candidate
        } else {
            current
        }
    }

    pub(super) fn assignment_target_and_rhs(stmt: &CStmt) -> Option<(crate::symbol::SymbolId, &CExpr)> {
        match stmt {
            CStmt::Expr(CExpr::Binary {
                op: BinaryOp::Assign,
                left,
                right,
            }) => {
                let CExpr::Var(name) = left.as_ref() else {
                    return None;
                };
                Some((*name, right.as_ref()))
            }
            CStmt::Decl {
                name,
                init: Some(init),
                ..
            } => Some((*name, init)),
            _ => None,
        }
    }
    pub(super) fn propagate_ephemeral_copies(&self, stmts: Vec<CStmt>) -> Vec<CStmt> {
        let mut aliases: HashMap<String, CExpr> = HashMap::new();
        let mut out = Vec::with_capacity(stmts.len());

        for stmt in stmts {
            let rewritten = self.rewrite_stmt_with_aliases(stmt, &aliases);
            let (_, def) = self.stmt_reads_and_def(&rewritten);
            if let Some(def_name) = def.map(|id| self.spelling(id)).as_deref() {
                self.invalidate_aliases_for_def(&mut aliases, def_name);
            }

            if let Some((target, rhs)) = Self::assignment_target_and_rhs(&rewritten)
                && (self.is_ephemeral_ssa_target(&self.spelling(target))
                    || (self.is_autogenerated_stack_home_name(&self.spelling(target))
                        && !self.state.return_stack_slots.iter().any(|offset| {
                            self.resolve_stack_var(*offset)
                                .is_some_and(|candidate| candidate.eq_ignore_ascii_case(&self.spelling(target)))
                        })))
                && self.expr_is_cheap_copy_rhs(rhs)
                && (self.prefers_visible_expr(&CExpr::Var(target), rhs)
                    || self.is_autogenerated_stack_home_name(&self.spelling(target)))
            {
                aliases.insert(self.spelling(target).to_string(), rhs.clone());
            }

            let clear_aliases =
                Self::stmt_clears_aliases(&rewritten) || Self::stmt_contains_call(&rewritten);
            out.push(rewritten);
            if clear_aliases {
                aliases.clear();
            }
        }

        out
    }

    fn rewrite_stmt_with_aliases(&self, stmt: CStmt, aliases: &HashMap<String, CExpr>) -> CStmt {
        match stmt {
            CStmt::Expr(CExpr::Binary {
                op: BinaryOp::Assign,
                left,
                right,
            }) => {
                let left = match *left {
                    CExpr::Var(name) => CExpr::Var(name),
                    other => {
                        let mut visiting = HashSet::new();
                        self.rewrite_expr_with_aliases(other, aliases, 0, &mut visiting)
                    }
                };
                let mut visiting = HashSet::new();
                let right = self.rewrite_expr_with_aliases(*right, aliases, 0, &mut visiting);
                CStmt::Expr(CExpr::assign(left, right))
            }
            CStmt::Expr(expr) => {
                let mut visiting = HashSet::new();
                CStmt::Expr(self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting))
            }
            CStmt::Decl { ty, name, init } => CStmt::Decl {
                ty,
                name,
                init: init.map(|expr| {
                    let mut visiting = HashSet::new();
                    self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting)
                }),
            },
            CStmt::Block(stmts) => CStmt::Block(
                stmts
                    .into_iter()
                    .map(|inner| self.rewrite_stmt_with_aliases(inner, aliases))
                    .collect(),
            ),
            CStmt::If {
                cond,
                then_body,
                else_body,
            } => {
                let mut visiting = HashSet::new();
                CStmt::If {
                    cond: self.rewrite_expr_with_aliases(cond, aliases, 0, &mut visiting),
                    then_body: Box::new(self.rewrite_stmt_with_aliases(*then_body, aliases)),
                    else_body: else_body
                        .map(|stmt| Box::new(self.rewrite_stmt_with_aliases(*stmt, aliases))),
                }
            }
            CStmt::While { cond, body } => {
                let mut visiting = HashSet::new();
                CStmt::While {
                    cond: self.rewrite_expr_with_aliases(cond, aliases, 0, &mut visiting),
                    body: Box::new(self.rewrite_stmt_with_aliases(*body, aliases)),
                }
            }
            CStmt::DoWhile { body, cond } => {
                let mut visiting = HashSet::new();
                CStmt::DoWhile {
                    body: Box::new(self.rewrite_stmt_with_aliases(*body, aliases)),
                    cond: self.rewrite_expr_with_aliases(cond, aliases, 0, &mut visiting),
                }
            }
            CStmt::For {
                init,
                cond,
                update,
                body,
            } => CStmt::For {
                init: init.map(|stmt| Box::new(self.rewrite_stmt_with_aliases(*stmt, aliases))),
                cond: cond.map(|expr| {
                    let mut visiting = HashSet::new();
                    self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting)
                }),
                update: update.map(|expr| {
                    let mut visiting = HashSet::new();
                    self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting)
                }),
                body: Box::new(self.rewrite_stmt_with_aliases(*body, aliases)),
            },
            CStmt::Switch {
                expr,
                cases,
                default,
            } => {
                let mut visiting = HashSet::new();
                CStmt::Switch {
                    expr: self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting),
                    cases: cases
                        .into_iter()
                        .map(|case| {
                            let mut case_visiting = HashSet::new();
                            crate::ast::SwitchCase {
                                value: self.rewrite_expr_with_aliases(
                                    case.value,
                                    aliases,
                                    0,
                                    &mut case_visiting,
                                ),
                                body: case
                                    .body
                                    .into_iter()
                                    .map(|stmt| self.rewrite_stmt_with_aliases(stmt, aliases))
                                    .collect(),
                            }
                        })
                        .collect(),
                    default: default.map(|stmts| {
                        stmts
                            .into_iter()
                            .map(|stmt| self.rewrite_stmt_with_aliases(stmt, aliases))
                            .collect()
                    }),
                }
            }
            CStmt::Return(expr) => CStmt::Return(expr.map(|expr| {
                let mut visiting = HashSet::new();
                self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting)
            })),
            other => other,
        }
    }

    fn rewrite_expr_with_aliases(
        &self,
        expr: CExpr,
        aliases: &HashMap<String, CExpr>,
        depth: u32,
        visiting: &mut HashSet<String>,
    ) -> CExpr {
        if depth > MAX_ALIAS_REWRITE_DEPTH {
            return expr;
        }

        match expr {
            CExpr::Var(name) => {
                let Some(alias) = aliases.get(&*self.spelling(name)).cloned() else {
                    return CExpr::Var(name);
                };

                if !visiting.insert(self.spelling(name).to_string()) {
                    return CExpr::Var(name);
                }

                let rewritten = self.rewrite_expr_with_aliases(alias, aliases, depth + 1, visiting);
                visiting.remove(&*self.spelling(name));
                self.choose_alias_rewrite(CExpr::Var(name), rewritten)
            }
            CExpr::Subscript { base, index } => CExpr::Subscript { base, index },
            CExpr::Member { base, member } => CExpr::Member { base, member },
            CExpr::PtrMember { base, member } => CExpr::PtrMember { base, member },
            other => other.map_children(&mut |child| {
                self.rewrite_expr_with_aliases(child, aliases, depth + 1, visiting)
            }),
        }
    }

    fn expr_is_cheap_copy_rhs(&self, expr: &CExpr) -> bool {
        match expr {
            CExpr::Var(_)
            | CExpr::IntLit(_)
            | CExpr::UIntLit(_)
            | CExpr::FloatLit(_)
            | CExpr::StringLit(_)
            | CExpr::CharLit(_) => true,
            CExpr::Paren(inner) | CExpr::Cast { expr: inner, .. } => {
                self.expr_is_cheap_copy_rhs(inner)
            }
            CExpr::Unary { operand, .. } => self.expr_is_cheap_copy_rhs(operand),
            _ => false,
        }
    }

    fn invalidate_aliases_for_def(&self, aliases: &mut HashMap<String, CExpr>, def_name: &str) {
        aliases.remove(def_name);
        aliases.retain(|_, expr| !self.expr_mentions_name(expr, def_name));
    }

    fn expr_mentions_name(&self, expr: &CExpr, name: &str) -> bool {
        let mut reads = HashSet::new();
        self.collect_expr_reads(expr, &mut reads);
        reads.contains(name)
    }

    fn stmt_clears_aliases(stmt: &CStmt) -> bool {
        matches!(
            stmt,
            CStmt::Label(_)
                | CStmt::Goto(_)
                | CStmt::Return(_)
                | CStmt::Break
                | CStmt::Continue
                | CStmt::If { .. }
                | CStmt::While { .. }
                | CStmt::DoWhile { .. }
                | CStmt::For { .. }
                | CStmt::Switch { .. }
                | CStmt::Block(_)
        )
    }

    fn stmt_contains_call(stmt: &CStmt) -> bool {
        let mut contains_call = false;
        match stmt {
            CStmt::Expr(expr)
            | CStmt::Return(Some(expr))
            | CStmt::While { cond: expr, .. }
            | CStmt::DoWhile { cond: expr, .. } => {
                expr.visit(&mut |node| {
                    if matches!(node, CExpr::Call { .. }) {
                        contains_call = true;
                    }
                });
            }
            CStmt::Decl {
                init: Some(expr), ..
            }
            | CStmt::If { cond: expr, .. }
            | CStmt::Switch { expr, .. } => {
                expr.visit(&mut |node| {
                    if matches!(node, CExpr::Call { .. }) {
                        contains_call = true;
                    }
                });
            }
            CStmt::For { cond, update, .. } => {
                for expr in cond.iter().chain(update.iter()) {
                    expr.visit(&mut |node| {
                        if matches!(node, CExpr::Call { .. }) {
                            contains_call = true;
                        }
                    });
                }
            }
            CStmt::Return(None)
            | CStmt::Decl { init: None, .. }
            | CStmt::Break
            | CStmt::Continue
            | CStmt::Goto(_)
            | CStmt::Label(_)
            | CStmt::Comment(_)
            | CStmt::Empty
            | CStmt::Block(_) => {}
        }
        contains_call
    }

    pub(super) fn expr_is_pure(&self, expr: &CExpr) -> bool {
        let mut pure = true;
        expr.visit(&mut |node| {
            if !pure {
                return;
            }
            match node {
                CExpr::Call { .. } => pure = false,
                CExpr::Binary { op, .. } => {
                    if matches!(
                        op,
                        BinaryOp::Assign
                            | BinaryOp::AddAssign
                            | BinaryOp::SubAssign
                            | BinaryOp::MulAssign
                            | BinaryOp::DivAssign
                            | BinaryOp::ModAssign
                            | BinaryOp::BitAndAssign
                            | BinaryOp::BitOrAssign
                            | BinaryOp::BitXorAssign
                            | BinaryOp::ShlAssign
                            | BinaryOp::ShrAssign
                    ) {
                        pure = false;
                    }
                }
                _ => {}
            }
        });
        pure
    }

    #[cfg(test)]
    pub(super) fn call_expr_returns_void(&self, expr: &CExpr) -> bool {
        let CExpr::Call { func, .. } = expr else {
            return false;
        };
        let Some(name) = Self::extract_callee_name(func) else {
            return false;
        };
        self.known_signature_for_callee_name(name)
            .is_some_and(|sig| matches!(sig.return_type, r2types::CTypeLike::Void))
    }

    pub(super) fn source_call_expr_returns_void(
        &self,
        source_call: (u64, usize),
        expr: &CExpr,
    ) -> bool {
        let CExpr::Call { .. } = expr else {
            return false;
        };
        self.expr_type_hint_for_source_call(source_call, expr)
            .is_some_and(|ty| matches!(ty, CType::Void))
    }

    pub(super) fn collect_expr_reads(&self, expr: &CExpr, out: &mut HashSet<String>) {
        expr.visit(&mut |node| {
            if let CExpr::Var(name) = node {
                out.insert(self.spelling(*name).to_string());
            }
        });
    }

    /// What a rendered statement reads and what it defines, for the render
    /// cleanups that run after structuring.
    pub(crate) fn stmt_reads_and_def_for_render(
        &self,
        stmt: &CStmt,
    ) -> (HashSet<String>, Option<crate::symbol::SymbolId>) {
        self.stmt_reads_and_def(stmt)
    }

    /// Whether a rendered statement copies a value into a versioned machine
    /// register carrier and does nothing else.
    pub(crate) fn stmt_is_side_effect_free_versioned_register_carrier_for_render(
        &self,
        stmt: &CStmt,
    ) -> bool {
        self.stmt_is_side_effect_free_versioned_register_carrier(stmt)
    }

    fn stmt_reads_and_def(&self, stmt: &CStmt) -> (HashSet<String>, Option<crate::symbol::SymbolId>) {
        let mut reads = HashSet::new();
        let mut def = None;

        match stmt {
            CStmt::Expr(CExpr::Binary {
                op: BinaryOp::Assign,
                left,
                right,
            }) => {
                if let CExpr::Var(name) = left.as_ref() {
                    def = Some(name.clone());
                } else {
                    self.collect_expr_reads(left, &mut reads);
                }
                self.collect_expr_reads(right, &mut reads);
            }
            CStmt::Expr(expr) => self.collect_expr_reads(expr, &mut reads),
            CStmt::Decl { name, init, .. } => {
                def = Some(name.clone());
                if let Some(expr) = init {
                    self.collect_expr_reads(expr, &mut reads);
                }
            }
            CStmt::If {
                cond,
                then_body,
                else_body,
            } => {
                self.collect_expr_reads(cond, &mut reads);
                let (then_reads, _) = self.stmt_reads_and_def(then_body);
                reads.extend(then_reads);
                if let Some(else_stmt) = else_body {
                    let (else_reads, _) = self.stmt_reads_and_def(else_stmt);
                    reads.extend(else_reads);
                }
            }
            CStmt::While { cond, body } | CStmt::DoWhile { cond, body } => {
                self.collect_expr_reads(cond, &mut reads);
                let (body_reads, _) = self.stmt_reads_and_def(body);
                reads.extend(body_reads);
            }
            CStmt::For {
                init,
                cond,
                update,
                body,
            } => {
                if let Some(init_stmt) = init {
                    let (init_reads, _) = self.stmt_reads_and_def(init_stmt);
                    reads.extend(init_reads);
                }
                if let Some(cond_expr) = cond {
                    self.collect_expr_reads(cond_expr, &mut reads);
                }
                if let Some(update_expr) = update {
                    self.collect_expr_reads(update_expr, &mut reads);
                }
                let (body_reads, _) = self.stmt_reads_and_def(body);
                reads.extend(body_reads);
            }
            CStmt::Switch {
                expr,
                cases,
                default,
            } => {
                self.collect_expr_reads(expr, &mut reads);
                for case in cases {
                    for stmt in &case.body {
                        let (case_reads, _) = self.stmt_reads_and_def(stmt);
                        reads.extend(case_reads);
                    }
                }
                if let Some(default_stmts) = default {
                    for stmt in default_stmts {
                        let (default_reads, _) = self.stmt_reads_and_def(stmt);
                        reads.extend(default_reads);
                    }
                }
            }
            CStmt::Return(Some(expr)) => self.collect_expr_reads(expr, &mut reads),
            CStmt::Block(stmts) => {
                for stmt in stmts {
                    let (stmt_reads, _) = self.stmt_reads_and_def(stmt);
                    reads.extend(stmt_reads);
                }
            }
            CStmt::Label(_)
            | CStmt::Goto(_)
            | CStmt::Break
            | CStmt::Continue
            | CStmt::Return(None)
            | CStmt::Comment(_)
            | CStmt::Empty => {}
        }

        (reads, def)
    }

    pub(super) fn prune_dead_temp_assignments(&self, stmts: Vec<CStmt>) -> Vec<CStmt> {
        self.prune_dead_temp_assignments_with_options(stmts, true, false)
    }

    pub(super) fn prune_dead_temp_assignments_before_structuring(
        &self,
        stmts: Vec<CStmt>,
    ) -> Vec<CStmt> {
        self.prune_dead_temp_assignments_with_options(stmts, false, true)
    }

    fn prune_dead_temp_assignments_with_options(
        &self,
        stmts: Vec<CStmt>,
        demote_dead_return_register_calls: bool,
        preserve_named_stack_owners: bool,
    ) -> Vec<CStmt> {
        let mut live = HashSet::new();
        let mut live_call_sources = BTreeSet::new();
        let mut live_call_assignment_sources = BTreeSet::new();
        let mut kept_rev = Vec::with_capacity(stmts.len());

        for stmt in stmts.into_iter().rev() {
            let mut stmt = stmt;
            let (mut reads, mut def) = self.stmt_reads_and_def(&stmt);

            let drop_stmt = if let Some((target, rhs)) = Self::assignment_target_and_rhs(&stmt) {
                let target_lower = self.spelling(target).to_ascii_lowercase();
                let target_is_pinned =
                    self.pinned_set().contains(&*self.spelling(target)) || self.pinned_set().contains(&target_lower);
                let source_call_for_target = self
                    .call_result_source_for_ssa_name(&self.spelling(target))
                    .or_else(|| self.local_post_call_source_for_ssa_name(&self.spelling(target)))
                    .or_else(|| self.source_call_for_visible_owner_name(&self.spelling(target)));
                let call_result_candidate_names = source_call_for_target
                    .map(|source_call| self.call_result_candidate_names(source_call, &self.spelling(target)))
                    .unwrap_or_default();
                let target_has_live_use = live.contains(&*self.spelling(target))
                    || call_result_candidate_names.iter().any(|candidate| {
                        candidate.eq_ignore_ascii_case(&self.spelling(target)) && live.contains(candidate)
                    });
                let dead_sleigh_memory_artifact = self.is_sleigh_memory_temp_name(&self.spelling(target))
                    && !target_has_live_use
                    && self.expr_contains_unresolved_memory(rhs);
                let observable_call_result_owner = self
                    .call_result_candidate_names_have_observable_use(&call_result_candidate_names);
                let rhs_call_source = matches!(rhs, CExpr::Call { .. })
                    .then_some(source_call_for_target)
                    .flatten();
                let target_is_named_stack_owner =
                    self.stack_slot_provenance_for_name(&self.spelling(target)).is_some()
                        || self.stack_offset_for_visible_storage_name(&self.spelling(target)).is_some()
                        || self
                            .certified_autogenerated_stack_storage_offset(&self.spelling(target))
                            .is_some();
                let target_is_materialized_call_owner = rhs_call_source.is_some_and(|source| {
                    self.stable_owned_call_result_name_for_source(source)
                        .is_some_and(|owner| owner.eq_ignore_ascii_case(&target_lower))
                });
                let protected_named_call_result_owner =
                    target_is_named_stack_owner && target_is_materialized_call_owner;
                let target_base = target_lower
                    .split('_')
                    .next()
                    .unwrap_or(&target_lower)
                    .to_ascii_lowercase();
                let dead_return_register_owner = demote_dead_return_register_calls
                    && self.inputs.arch.is_return_register_name(&target_base);
                let dead_transient_call_result = !target_has_live_use
                    && !target_is_pinned
                    && (dead_return_register_owner
                        || !observable_call_result_owner
                        || rhs_call_source
                            .is_some_and(|source| self.source_call_expr_returns_void(source, rhs)))
                    && matches!(rhs, CExpr::Call { .. })
                    && !protected_named_call_result_owner
                    && (self.is_low_signal_visible_name(&self.spelling(target))
                        || self.is_prunable_dead_binding_target(&self.spelling(target)));
                let dead_ephemeral = self.is_prunable_dead_binding_target(&self.spelling(target))
                    && !target_is_pinned
                    && !target_has_live_use
                    && (!preserve_named_stack_owners || !target_is_named_stack_owner)
                    && (self.expr_is_pure(rhs) || dead_sleigh_memory_artifact);
                let dead_flag_artifact =
                    is_cpu_flag(&target_lower) && !target_has_live_use && self.expr_is_pure(rhs);

                // A call is an event, so a statement carrying one can lose its
                // target when nothing reads the result, but it can never be
                // deleted: the program still makes the call. Deciding that a
                // second rendering of the same site is redundant is not this
                // pass's judgement to make -- rendering each site once is
                // settled before the output is pruned.
                if dead_transient_call_result {
                    stmt = CStmt::Expr(rhs.clone());
                    (reads, def) = self.stmt_reads_and_def(&stmt);
                    false
                } else {
                    dead_ephemeral || dead_flag_artifact
                }
            } else {
                // A statement that is only an expression, and whose evaluation
                // does nothing, says nothing. Naming a value without using it
                // is not an observation the program makes.
                matches!(&stmt, CStmt::Expr(expr) if self.expr_is_pure(expr))
            };

            if drop_stmt {
                continue;
            }

            if let Some(def_name) = def {
                live.remove(&*self.spelling(def_name));
            }
            live.extend(reads);
            self.collect_call_sources_in_stmt(&stmt, &mut live_call_sources);
            self.collect_call_assignment_sources_in_stmt(&stmt, &mut live_call_assignment_sources);
            kept_rev.push(stmt);
        }

        kept_rev.reverse();
        kept_rev
    }

    pub(crate) fn prune_dead_temp_assignments_in_stmt(&self, stmt: CStmt) -> CStmt {
        match stmt {
            CStmt::Block(stmts) => CStmt::Block(self.prune_dead_temp_assignments_in_block(stmts)),
            CStmt::If {
                cond,
                then_body,
                else_body,
            } => CStmt::If {
                cond,
                then_body: Box::new(self.prune_dead_temp_assignments_in_stmt(*then_body)),
                else_body: else_body
                    .map(|stmt| Box::new(self.prune_dead_temp_assignments_in_stmt(*stmt))),
            },
            CStmt::While { cond, body } => CStmt::While {
                cond,
                body: Box::new(self.prune_dead_temp_assignments_in_stmt(*body)),
            },
            CStmt::DoWhile { body, cond } => CStmt::DoWhile {
                body: Box::new(self.prune_dead_temp_assignments_in_stmt(*body)),
                cond,
            },
            CStmt::For {
                init,
                cond,
                update,
                body,
            } => CStmt::For {
                init: init.map(|stmt| Box::new(self.prune_dead_temp_assignments_in_stmt(*stmt))),
                cond,
                update,
                body: Box::new(self.prune_dead_temp_assignments_in_stmt(*body)),
            },
            CStmt::Switch {
                expr,
                cases,
                default,
            } => CStmt::Switch {
                expr,
                cases: cases
                    .into_iter()
                    .map(|case| crate::ast::SwitchCase {
                        value: case.value,
                        body: self.prune_dead_temp_assignments_in_block(case.body),
                    })
                    .collect(),
                default: default.map(|stmts| self.prune_dead_temp_assignments_in_block(stmts)),
            },
            other => other,
        }
    }

    pub(super) fn stmt_is_side_effect_free_versioned_register_carrier(&self, stmt: &CStmt) -> bool {
        let Some(name) = super::side_effect_free_assignment_name(stmt) else {
            return false;
        };
        let lower = self.spelling(name).to_ascii_lowercase();
        let Some((base, version)) = lower.rsplit_once('_') else {
            return false;
        };
        !version.is_empty()
            && version.bytes().all(|byte| byte.is_ascii_digit())
            && self.inputs.arch.is_register_like_base_name(base)
    }

    fn prune_dead_temp_assignments_in_block(&self, stmts: Vec<CStmt>) -> Vec<CStmt> {
        let rewritten = stmts
            .into_iter()
            .map(|stmt| self.prune_dead_temp_assignments_in_stmt(stmt))
            .collect();
        self.prune_dead_temp_assignments(rewritten)
    }

    fn collect_call_sources_in_stmt(&self, stmt: &CStmt, out: &mut BTreeSet<(u64, usize)>) {
        match stmt {
            CStmt::Expr(expr)
            | CStmt::Return(Some(expr))
            | CStmt::While { cond: expr, .. }
            | CStmt::DoWhile { cond: expr, .. } => self.collect_call_sources_in_expr(expr, out),
            CStmt::Decl {
                init: Some(expr), ..
            } => self.collect_call_sources_in_expr(expr, out),
            CStmt::If { cond, .. } => self.collect_call_sources_in_expr(cond, out),
            CStmt::For {
                cond: Some(expr),
                update: Some(update),
                ..
            } => {
                self.collect_call_sources_in_expr(expr, out);
                self.collect_call_sources_in_expr(update, out);
            }
            CStmt::For {
                cond: Some(expr),
                update: None,
                ..
            }
            | CStmt::For {
                cond: None,
                update: Some(expr),
                ..
            } => self.collect_call_sources_in_expr(expr, out),
            CStmt::Switch { expr, .. } => self.collect_call_sources_in_expr(expr, out),
            CStmt::Return(None)
            | CStmt::Decl { init: None, .. }
            | CStmt::Break
            | CStmt::Continue
            | CStmt::Goto(_)
            | CStmt::Label(_)
            | CStmt::Comment(_)
            | CStmt::Empty
            | CStmt::Block(_)
            | CStmt::For {
                cond: None,
                update: None,
                ..
            } => {}
        }
    }

    fn collect_call_sources_in_expr(&self, expr: &CExpr, out: &mut BTreeSet<(u64, usize)>) {
        expr.visit(&mut |node| {
            if let CExpr::Var(name) = node
                && let Some(source) = self
                    .call_result_source_for_ssa_name(&self.spelling(*name))
                    .or_else(|| self.local_post_call_source_for_ssa_name(&self.spelling(*name)))
                    .or_else(|| self.materialized_call_result_source_for_visible_name(*name))
            {
                out.insert(source);
            }
        });
    }

    fn collect_call_assignment_sources_in_stmt(
        &self,
        stmt: &CStmt,
        out: &mut BTreeSet<((u64, usize), String)>,
    ) {
        let CStmt::Expr(CExpr::Binary {
            op: BinaryOp::Assign,
            left,
            right,
        }) = stmt
        else {
            return;
        };
        let CExpr::Var(target) = left.as_ref() else {
            return;
        };
        if !matches!(right.as_ref(), CExpr::Call { .. }) {
            return;
        }
        if let Some(source) = self
            .call_result_source_for_ssa_name(&self.spelling(*target))
            .or_else(|| self.local_post_call_source_for_ssa_name(&self.spelling(*target)))
            .or_else(|| self.source_call_for_visible_owner_name(&self.spelling(*target)))
        {
            out.insert((source, self.spelling(*target).to_ascii_lowercase()));
        }
    }
}
