use super::*;

impl<'a> FoldingContext<'a> {
    pub(super) fn is_prunable_dead_binding_target(&self, name: &str) -> bool {
        if !self.state.return_stack_slots.is_empty()
            && self.is_autogenerated_stack_home_name(name)
        {
            return false;
        }
        if self.is_ephemeral_ssa_target(name) {
            return true;
        }
        let lower = name.to_ascii_lowercase();
        lower == "stack"
            || lower.starts_with("value_")
            || self.is_autogenerated_stack_home_name(name)
    }

    fn alias_rewrite_keeps_semantics(&self, current: &CExpr, candidate: &CExpr) -> bool {
        if self.expr_contains_generic_stack_alias(candidate)
            || self.is_uninitialized_return_reg(candidate)
        {
            return false;
        }

        match current.unobserved() {
            CExpr::Subscript { .. } | CExpr::Member { .. } | CExpr::PtrMember { .. } => {
                matches!(
                    candidate.unobserved(),
                    CExpr::Subscript { .. } | CExpr::Member { .. } | CExpr::PtrMember { .. }
                )
            }
            CExpr::Var(_) => true,
            _ => true,
        }
    }

    fn choose_alias_rewrite(&self, current: CExpr, candidate: CExpr) -> CExpr {
        if self.is_preservable_named_stack_slot_expr(&current)
            && self.is_direct_constish_visible_expr(&candidate, 0)
        {
            return current;
        }
        if let CExpr::Var(name) = current.unobserved()
            && self.is_autogenerated_stack_home_name(&self.spelling(*name))
            && self.alias_rewrite_keeps_semantics(&current, &candidate)
        {
            return candidate;
        }
        if self.prefers_visible_expr(&current, &candidate)
            && self.alias_rewrite_keeps_semantics(&current, &candidate)
        {
            candidate
        } else {
            current
        }
    }

    pub(super) fn assignment_target_and_rhs(
        stmt: &CStmt,
    ) -> Option<(crate::symbol::SymbolId, &CExpr)> {
        match stmt.unobserved() {
            CStmt::Expr(expr) => {
                let CExpr::Binary {
                op: BinaryOp::Assign,
                left,
                right,
                } = expr.unobserved()
                else {
                    return None;
                };
                let CExpr::Var(name) = left.unobserved() else {
                    return None;
                };
                Some((*name, right.as_ref()))
            }
            CStmt::Decl {
                name,
                init: Some(init),
                ..
            } => Some((*name, init)),
            _ => None,
        }
    }
    pub(super) fn propagate_ephemeral_copies(&self, stmts: Vec<CStmt>) -> Vec<CStmt> {
        // This is a presentation rewrite over already-authorized SymbolIds.
        // It must never recover identity from a spelling.
        let mut aliases: HashMap<crate::symbol::SymbolId, CExpr> = HashMap::new();
        let mut out = Vec::with_capacity(stmts.len());

        for stmt in stmts {
            let rewritten = self.rewrite_stmt_with_aliases(stmt, &aliases);
            let (_, def) = self.stmt_reads_and_def(&rewritten);
            if let Some(definition) = def {
                self.invalidate_aliases_for_def(&mut aliases, definition);
            }

            if let Some((target, rhs)) = Self::assignment_target_and_rhs(&rewritten)
                && (self.is_ephemeral_ssa_target(&self.spelling(target))
                    || (self.is_autogenerated_stack_home_name(&self.spelling(target))
                        && self.state.return_stack_slots.is_empty()))
                && self.expr_is_cheap_copy_rhs(rhs)
                && (self.prefers_visible_expr(&CExpr::Var(target), rhs)
                    || self.is_autogenerated_stack_home_name(&self.spelling(target)))
            {
                aliases.insert(target, rhs.clone_without_render_observations());
            }

            let clear_aliases =
                Self::stmt_clears_aliases(&rewritten) || Self::stmt_contains_call(&rewritten);
            out.push(rewritten);
            if clear_aliases {
                aliases.clear();
            }
        }

        out
    }

    fn rewrite_stmt_with_aliases(
        &self,
        stmt: CStmt,
        aliases: &HashMap<crate::symbol::SymbolId, CExpr>,
    ) -> CStmt {
        match stmt {
            CStmt::Expr(expr) => {
                let mut visiting = HashSet::new();
                CStmt::Expr(self.rewrite_statement_expr_with_aliases(
                    expr,
                    aliases,
                    0,
                    &mut visiting,
                ))
            }
            CStmt::Observed { id, stmt } => {
                CStmt::observed(id, self.rewrite_stmt_with_aliases(*stmt, aliases))
            }
            CStmt::Decl { ty, name, init } => CStmt::Decl {
                ty,
                name,
                init: init.map(|expr| {
                    let mut visiting = HashSet::new();
                    self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting)
                }),
            },
            CStmt::Block(stmts) => CStmt::Block(
                stmts
                    .into_iter()
                    .map(|inner| self.rewrite_stmt_with_aliases(inner, aliases))
                    .collect(),
            ),
            CStmt::If {
                cond,
                then_body,
                else_body,
            } => {
                let mut visiting = HashSet::new();
                CStmt::If {
                    cond: self.rewrite_expr_with_aliases(cond, aliases, 0, &mut visiting),
                    then_body: Box::new(self.rewrite_stmt_with_aliases(*then_body, aliases)),
                    else_body: else_body
                        .map(|stmt| Box::new(self.rewrite_stmt_with_aliases(*stmt, aliases))),
                }
            }
            CStmt::While { cond, body } => {
                let mut visiting = HashSet::new();
                CStmt::While {
                    cond: self.rewrite_expr_with_aliases(cond, aliases, 0, &mut visiting),
                    body: Box::new(self.rewrite_stmt_with_aliases(*body, aliases)),
                }
            }
            CStmt::DoWhile { body, cond } => {
                let mut visiting = HashSet::new();
                CStmt::DoWhile {
                    body: Box::new(self.rewrite_stmt_with_aliases(*body, aliases)),
                    cond: self.rewrite_expr_with_aliases(cond, aliases, 0, &mut visiting),
                }
            }
            CStmt::For {
                init,
                cond,
                update,
                body,
            } => CStmt::For {
                init: init.map(|stmt| Box::new(self.rewrite_stmt_with_aliases(*stmt, aliases))),
                cond: cond.map(|expr| {
                    let mut visiting = HashSet::new();
                    self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting)
                }),
                update: update.map(|expr| {
                    let mut visiting = HashSet::new();
                    self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting)
                }),
                body: Box::new(self.rewrite_stmt_with_aliases(*body, aliases)),
            },
            CStmt::Switch {
                expr,
                cases,
                default,
            } => {
                let mut visiting = HashSet::new();
                CStmt::Switch {
                    expr: self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting),
                    cases: cases
                        .into_iter()
                        .map(|case| {
                            let mut case_visiting = HashSet::new();
                            crate::ast::SwitchCase {
                                value: self.rewrite_expr_with_aliases(
                                    case.value,
                                    aliases,
                                    0,
                                    &mut case_visiting,
                                ),
                                body: case
                                    .body
                                    .into_iter()
                                    .map(|stmt| self.rewrite_stmt_with_aliases(stmt, aliases))
                                    .collect(),
                            }
                        })
                        .collect(),
                    default: default.map(|stmts| {
                        stmts
                            .into_iter()
                            .map(|stmt| self.rewrite_stmt_with_aliases(stmt, aliases))
                            .collect()
                    }),
                }
            }
            CStmt::Return(expr) => CStmt::Return(expr.map(|expr| {
                let mut visiting = HashSet::new();
                self.rewrite_expr_with_aliases(expr, aliases, 0, &mut visiting)
            })),
            other => other,
        }
    }

    fn rewrite_statement_expr_with_aliases(
        &self,
        expr: CExpr,
        aliases: &HashMap<crate::symbol::SymbolId, CExpr>,
        depth: u32,
        visiting: &mut HashSet<crate::symbol::SymbolId>,
    ) -> CExpr {
        match expr {
            CExpr::Observed { id, expr } => CExpr::observed(
                id,
                self.rewrite_statement_expr_with_aliases(
                    *expr,
                    aliases,
                    depth,
                    visiting,
                ),
            ),
            CExpr::Binary {
                op: BinaryOp::Assign,
                left,
                right,
            } => {
                let left = if matches!(left.unobserved(), CExpr::Var(_)) {
                    *left
                } else {
                    self.rewrite_expr_with_aliases(*left, aliases, depth, visiting)
                };
                let right = self.rewrite_expr_with_aliases(*right, aliases, depth, visiting);
                CExpr::assign(left, right)
            }
            other => self.rewrite_expr_with_aliases(other, aliases, depth, visiting),
        }
    }

    fn rewrite_expr_with_aliases(
        &self,
        expr: CExpr,
        aliases: &HashMap<crate::symbol::SymbolId, CExpr>,
        depth: u32,
        visiting: &mut HashSet<crate::symbol::SymbolId>,
    ) -> CExpr {
        if depth > MAX_ALIAS_REWRITE_DEPTH {
            return expr;
        }

        match expr {
            CExpr::Observed { id, expr } => CExpr::observed(
                id,
                self.rewrite_expr_with_aliases(*expr, aliases, depth, visiting),
            ),
            CExpr::Var(name) => {
                let Some(alias) = aliases.get(&name).cloned() else {
                    return CExpr::Var(name);
                };

                if !visiting.insert(name) {
                    return CExpr::Var(name);
                }

                let rewritten = self.rewrite_expr_with_aliases(alias, aliases, depth + 1, visiting);
                visiting.remove(&name);
                self.choose_alias_rewrite(CExpr::Var(name), rewritten)
            }
            CExpr::Subscript { base, index } => CExpr::Subscript { base, index },
            CExpr::Member { base, member } => CExpr::Member { base, member },
            CExpr::PtrMember { base, member } => CExpr::PtrMember { base, member },
            other => other.map_children(&mut |child| {
                self.rewrite_expr_with_aliases(child, aliases, depth + 1, visiting)
            }),
        }
    }

    fn expr_is_cheap_copy_rhs(&self, expr: &CExpr) -> bool {
        match expr.unobserved() {
            CExpr::Var(_)
            | CExpr::IntLit(_)
            | CExpr::UIntLit(_)
            | CExpr::FloatLit(_)
            | CExpr::StringLit(_)
            | CExpr::CharLit(_) => true,
            CExpr::Paren(inner) | CExpr::Cast { expr: inner, .. } => {
                self.expr_is_cheap_copy_rhs(inner)
            }
            CExpr::Unary { operand, .. } => self.expr_is_cheap_copy_rhs(operand),
            _ => false,
        }
    }

    fn invalidate_aliases_for_def(
        &self,
        aliases: &mut HashMap<crate::symbol::SymbolId, CExpr>,
        definition: crate::symbol::SymbolId,
    ) {
        aliases.remove(&definition);
        aliases.retain(|_, expr| !self.expr_mentions_symbol(expr, definition));
    }

    fn expr_mentions_symbol(&self, expr: &CExpr, symbol: crate::symbol::SymbolId) -> bool {
        let mut found = false;
        expr.visit(&mut |node| {
            if matches!(node, CExpr::Var(candidate) if *candidate == symbol) {
                found = true;
            }
        });
        found
    }

    fn stmt_clears_aliases(stmt: &CStmt) -> bool {
        if let CStmt::StructuredRegion { stmt, .. } = stmt {
            return Self::stmt_clears_aliases(stmt);
        }
        matches!(
            stmt.unobserved(),
            CStmt::Label(_)
                | CStmt::Goto(_)
                | CStmt::Return(_)
                | CStmt::Break
                | CStmt::Continue
                | CStmt::If { .. }
                | CStmt::While { .. }
                | CStmt::DoWhile { .. }
                | CStmt::For { .. }
                | CStmt::Switch { .. }
                | CStmt::Block(_)
        )
    }

    fn stmt_contains_call(stmt: &CStmt) -> bool {
        let mut contains_call = false;
        match stmt {
            CStmt::StructuredRegion { stmt, .. } => return Self::stmt_contains_call(stmt),
            CStmt::Observed { stmt, .. } => return Self::stmt_contains_call(stmt),
            CStmt::Expr(expr)
            | CStmt::Return(Some(expr))
            | CStmt::While { cond: expr, .. }
            | CStmt::DoWhile { cond: expr, .. } => {
                expr.visit(&mut |node| {
                    if matches!(node, CExpr::Call { .. }) {
                        contains_call = true;
                    }
                });
            }
            CStmt::Decl {
                init: Some(expr), ..
            }
            | CStmt::If { cond: expr, .. }
            | CStmt::Switch { expr, .. } => {
                expr.visit(&mut |node| {
                    if matches!(node, CExpr::Call { .. }) {
                        contains_call = true;
                    }
                });
            }
            CStmt::For { cond, update, .. } => {
                for expr in cond.iter().chain(update.iter()) {
                    expr.visit(&mut |node| {
                        if matches!(node, CExpr::Call { .. }) {
                            contains_call = true;
                        }
                    });
                }
            }
            CStmt::Return(None)
            | CStmt::Decl { init: None, .. }
            | CStmt::Break
            | CStmt::Continue
            | CStmt::Goto(_)
            | CStmt::Label(_)
            | CStmt::Comment(_)
            | CStmt::Empty
            | CStmt::Block(_) => {}
        }
        contains_call
    }

    pub(super) fn expr_is_pure(&self, expr: &CExpr) -> bool {
        let mut pure = true;
        expr.visit(&mut |node| {
            if !pure {
                return;
            }
            match node {
                CExpr::Call { .. } => pure = false,
                CExpr::Binary { op, .. } => {
                    if matches!(
                        op,
                        BinaryOp::Assign
                            | BinaryOp::AddAssign
                            | BinaryOp::SubAssign
                            | BinaryOp::MulAssign
                            | BinaryOp::DivAssign
                            | BinaryOp::ModAssign
                            | BinaryOp::BitAndAssign
                            | BinaryOp::BitOrAssign
                            | BinaryOp::BitXorAssign
                            | BinaryOp::ShlAssign
                            | BinaryOp::ShrAssign
                    ) {
                        pure = false;
                    }
                }
                _ => {}
            }
        });
        pure
    }

    #[cfg(test)]
    pub(super) fn call_expr_returns_void(&self, expr: &CExpr) -> bool {
        let CExpr::Call { func, .. } = expr.unobserved() else {
            return false;
        };
        let Some(name) = self.extract_callee_name(func) else {
            return false;
        };
        self.known_signature_for_callee_name(&name)
            .is_some_and(|sig| matches!(sig.return_type, r2types::CTypeLike::Void))
    }

    #[cfg(test)]
    pub(super) fn source_call_expr_returns_void(
        &self,
        source_call: (u64, usize),
        expr: &CExpr,
    ) -> bool {
        let semantic_expr = expr.unobserved();
        let CExpr::Call { .. } = semantic_expr else {
            return false;
        };
        self.expr_type_hint_for_source_call(source_call, semantic_expr)
            .is_some_and(|ty| matches!(ty, CType::Void))
    }

    pub(super) fn collect_expr_reads(
        &self,
        expr: &CExpr,
        out: &mut HashSet<crate::symbol::SymbolId>,
    ) {
        expr.visit(&mut |node| {
            if let CExpr::Var(name) = node {
                out.insert(*name);
            }
        });
    }

    /// What a rendered statement reads and what it defines, for the render
    /// cleanups that run after structuring.
    pub(crate) fn stmt_reads_and_def_for_render(
        &self,
        stmt: &CStmt,
    ) -> (
        HashSet<crate::symbol::SymbolId>,
        Option<crate::symbol::SymbolId>,
    ) {
        self.stmt_reads_and_def(stmt)
    }

    /// Whether a rendered statement copies a value into a versioned machine
    /// register carrier and does nothing else.
    pub(crate) fn stmt_is_side_effect_free_versioned_register_carrier_for_render(
        &self,
        stmt: &CStmt,
    ) -> bool {
        self.stmt_is_side_effect_free_versioned_register_carrier(stmt)
    }

    fn stmt_reads_and_def(
        &self,
        stmt: &CStmt,
    ) -> (
        HashSet<crate::symbol::SymbolId>,
        Option<crate::symbol::SymbolId>,
    ) {
        let mut reads = HashSet::new();
        let mut def = None;

        match stmt {
            CStmt::StructuredRegion { stmt, .. } => return self.stmt_reads_and_def(stmt),
            CStmt::Observed { stmt, .. } => return self.stmt_reads_and_def(stmt),
            CStmt::Expr(expr) => {
                if let CExpr::Binary {
                    op: BinaryOp::Assign,
                    left,
                    right,
                } = expr.unobserved()
                {
                    if let CExpr::Var(name) = left.unobserved() {
                        def = Some(*name);
                    } else {
                        self.collect_expr_reads(left, &mut reads);
                    }
                    self.collect_expr_reads(right, &mut reads);
                } else {
                    self.collect_expr_reads(expr, &mut reads);
                }
            }
            CStmt::Decl { name, init, .. } => {
                def = Some(name.clone());
                if let Some(expr) = init {
                    self.collect_expr_reads(expr, &mut reads);
                }
            }
            CStmt::If {
                cond,
                then_body,
                else_body,
            } => {
                self.collect_expr_reads(cond, &mut reads);
                let (then_reads, _) = self.stmt_reads_and_def(then_body);
                reads.extend(then_reads);
                if let Some(else_stmt) = else_body {
                    let (else_reads, _) = self.stmt_reads_and_def(else_stmt);
                    reads.extend(else_reads);
                }
            }
            CStmt::While { cond, body } | CStmt::DoWhile { cond, body } => {
                self.collect_expr_reads(cond, &mut reads);
                let (body_reads, _) = self.stmt_reads_and_def(body);
                reads.extend(body_reads);
            }
            CStmt::For {
                init,
                cond,
                update,
                body,
            } => {
                if let Some(init_stmt) = init {
                    let (init_reads, _) = self.stmt_reads_and_def(init_stmt);
                    reads.extend(init_reads);
                }
                if let Some(cond_expr) = cond {
                    self.collect_expr_reads(cond_expr, &mut reads);
                }
                if let Some(update_expr) = update {
                    self.collect_expr_reads(update_expr, &mut reads);
                }
                let (body_reads, _) = self.stmt_reads_and_def(body);
                reads.extend(body_reads);
            }
            CStmt::Switch {
                expr,
                cases,
                default,
            } => {
                self.collect_expr_reads(expr, &mut reads);
                for case in cases {
                    for stmt in &case.body {
                        let (case_reads, _) = self.stmt_reads_and_def(stmt);
                        reads.extend(case_reads);
                    }
                }
                if let Some(default_stmts) = default {
                    for stmt in default_stmts {
                        let (default_reads, _) = self.stmt_reads_and_def(stmt);
                        reads.extend(default_reads);
                    }
                }
            }
            CStmt::Return(Some(expr)) => self.collect_expr_reads(expr, &mut reads),
            CStmt::Block(stmts) => {
                for stmt in stmts {
                    let (stmt_reads, _) = self.stmt_reads_and_def(stmt);
                    reads.extend(stmt_reads);
                }
            }
            CStmt::Label(_)
            | CStmt::Goto(_)
            | CStmt::Break
            | CStmt::Continue
            | CStmt::Return(None)
            | CStmt::Comment(_)
            | CStmt::Empty => {}
        }

        (reads, def)
    }

    #[cfg(test)]
    pub(super) fn prune_dead_temp_assignments(&self, stmts: Vec<CStmt>) -> Vec<CStmt> {
        self.prune_dead_temp_assignments_with_options(stmts, true, false)
    }

    pub(super) fn prune_dead_temp_assignments_before_structuring(
        &self,
        stmts: Vec<CStmt>,
    ) -> Vec<CStmt> {
        self.prune_dead_temp_assignments_with_options(stmts, false, true)
    }

    fn prune_dead_temp_assignments_with_options(
        &self,
        stmts: Vec<CStmt>,
        demote_dead_return_register_calls: bool,
        preserve_named_stack_owners: bool,
    ) -> Vec<CStmt> {
        self.prune_dead_temp_assignments_with_options_and_live_out(
            stmts,
            demote_dead_return_register_calls,
            preserve_named_stack_owners,
            &HashSet::new(),
        )
    }

    /// Which assignments in this statement list nothing goes on to read.
    ///
    /// Liveness is decided by walking the list backwards, so a name read only
    /// *outside* the list has to be given here. It used to start empty for every
    /// list, and a list is a block: the body of a loop was pruned knowing nothing
    /// about the loop's condition, the statements after the loop, or its own next
    /// iteration. `adler32` assigns `b = (b + a) % 65521` in its loop and reads
    /// `b` in the `return`, so the assignment looked dead and the rendering
    /// returned the value `b` was initialised with -- the right low half and a
    /// zero high half, from C that a reader has no reason to doubt.
    fn prune_dead_temp_assignments_with_options_and_live_out(
        &self,
        stmts: Vec<CStmt>,
        demote_dead_return_register_calls: bool,
        _preserve_named_stack_owners: bool,
        live_out: &HashSet<crate::symbol::SymbolId>,
    ) -> Vec<CStmt> {
        let mut live: HashSet<crate::symbol::SymbolId> = live_out.clone();
        let mut kept_rev = Vec::with_capacity(stmts.len());

        for stmt in stmts.into_iter().rev() {
            let mut stmt = stmt;
            let (mut reads, mut def) = self.stmt_reads_and_def(&stmt);

            let drop_stmt = if let Some((target, rhs)) = Self::assignment_target_and_rhs(&stmt) {
                let target_is_exact_local = self
                    .inputs
                    .binding_names
                    .is_some_and(|names| names.authorizes_program_variable(target))
                    && matches!(
                        self.symbols.borrow().get(target).role,
                        crate::symbol::SymbolRole::Carrier
                    );
                let target_has_live_use = live.contains(&target);

                // The remaining pinned/cross-block sets have no BindingId or
                // SymbolId key yet. While either contains an unprojected fact,
                // it cannot safely authorize deletion of any particular
                // assignment by comparing presentation text.
                let has_unprojected_liveness = !self.pinned_set().is_empty()
                    || !self.cross_block_reads.borrow().is_empty();

                // The call occurrence retains its exact upstream site. A bare
                // assignment target does not identify a result value, so no
                // alias/owner spelling is consulted. Without the site, keep the
                // assignment conservatively.
                let exact_call_site = match rhs.unobserved() {
                    CExpr::Call {
                        site: Some(source),
                        ..
                    } => Some(*source),
                    _ => None,
                };
                let dead_exact_call_result = demote_dead_return_register_calls
                    && target_is_exact_local
                    && !target_has_live_use
                    && !has_unprojected_liveness
                    && exact_call_site.is_some();

                // A call is an event, so a statement carrying one can lose its
                // target when nothing reads the result, but it can never be
                // deleted: the program still makes the call. Deciding that a
                // second rendering of the same site is redundant is not this
                // pass's judgement to make -- rendering each site once is
                // settled before the output is pruned.
                if dead_exact_call_result {
                    // The call occurrence survives, but the assignment/write
                    // occurrence does not. Keeping the RHS preserves its own
                    // markers; moving the statement marker would credit a
                    // write that is absent from the emitted C.
                    stmt = CStmt::Expr(rhs.clone());
                    (reads, def) = self.stmt_reads_and_def(&stmt);
                    false
                } else {
                    // This AST occurrence carries no ValueId/UseSite. Pure
                    // assignment deletion therefore waits for exact occurrence
                    // provenance instead of guessing from a temporary, flag,
                    // register, or stack-looking spelling.
                    false
                }
            } else {
                // A statement that is only an expression, and whose evaluation
                // does nothing, says nothing. Naming a value without using it
                // is not an observation the program makes.
                matches!(stmt.unobserved(), CStmt::Expr(expr) if self.expr_is_pure(expr))
            };

            if drop_stmt {
                continue;
            }

            if let Some(def_name) = def {
                live.remove(&def_name);
            }
            live.extend(reads);
            kept_rev.push(stmt);
        }

        kept_rev.reverse();
        kept_rev
    }

    pub(super) fn stmt_is_side_effect_free_versioned_register_carrier(&self, stmt: &CStmt) -> bool {
        let _ = stmt;
        // A SymbolId identifies a rendered binding, not the machine location
        // of this assignment occurrence. Until the statement carries its exact
        // write projection, treating a suffix-shaped name as a register write
        // would make an unproved effect-elision decision.
        false
    }

    pub(crate) fn prune_dead_temp_assignments_in_stmt(&self, stmt: CStmt) -> CStmt {
        // Nothing outside a function reads its locals, so the body starts with
        // nothing live. Every nested list gets what its surroundings read.
        self.prune_dead_temp_assignments_in_stmt_live_out(stmt, &HashSet::new())
    }

    /// Every exact rendered symbol this statement reads.
    fn names_read_in_stmt(&self, stmt: &CStmt) -> HashSet<crate::symbol::SymbolId> {
        crate::collect_stmt_var_names(std::slice::from_ref(stmt))
            .into_iter()
            .collect()
    }

    fn prune_dead_temp_assignments_in_stmt_live_out(
        &self,
        stmt: CStmt,
        live_out: &HashSet<crate::symbol::SymbolId>,
    ) -> CStmt {
        match stmt {
            CStmt::Observed { id, stmt } => CStmt::observed(
                id,
                self.prune_dead_temp_assignments_in_stmt_live_out(*stmt, live_out),
            ),
            CStmt::Block(stmts) => {
                CStmt::Block(self.prune_dead_temp_assignments_in_block(stmts, live_out))
            }
            CStmt::If {
                cond,
                then_body,
                else_body,
            } => CStmt::If {
                cond,
                then_body: Box::new(
                    self.prune_dead_temp_assignments_in_stmt_live_out(*then_body, live_out),
                ),
                else_body: else_body.map(|stmt| {
                    Box::new(self.prune_dead_temp_assignments_in_stmt_live_out(*stmt, live_out))
                }),
            },
            // A loop body runs again, so whatever the loop reads anywhere -- its
            // condition, its update, or the body itself on the next iteration --
            // is live at the end of one pass through it.
            CStmt::While { cond, body } => {
                let mut inner = live_out.clone();
                inner.extend(self.names_read_in_stmt(&CStmt::Expr(cond.clone())));
                inner.extend(self.names_read_in_stmt(&body));
                CStmt::While {
                    cond,
                    body: Box::new(
                        self.prune_dead_temp_assignments_in_stmt_live_out(*body, &inner),
                    ),
                }
            }
            CStmt::DoWhile { body, cond } => {
                let mut inner = live_out.clone();
                inner.extend(self.names_read_in_stmt(&CStmt::Expr(cond.clone())));
                inner.extend(self.names_read_in_stmt(&body));
                CStmt::DoWhile {
                    body: Box::new(
                        self.prune_dead_temp_assignments_in_stmt_live_out(*body, &inner),
                    ),
                    cond,
                }
            }
            CStmt::For {
                init,
                cond,
                update,
                body,
            } => {
                let mut inner = live_out.clone();
                if let Some(cond) = cond.as_ref() {
                    inner.extend(self.names_read_in_stmt(&CStmt::Expr(cond.clone())));
                }
                if let Some(update) = update.as_ref() {
                    inner.extend(self.names_read_in_stmt(&CStmt::Expr(update.clone())));
                }
                inner.extend(self.names_read_in_stmt(&body));
                let body =
                    Box::new(self.prune_dead_temp_assignments_in_stmt_live_out(*body, &inner));
                CStmt::For {
                    init: init.map(|stmt| {
                        Box::new(self.prune_dead_temp_assignments_in_stmt_live_out(*stmt, &inner))
                    }),
                    cond,
                    update,
                    body,
                }
            }
            CStmt::Switch {
                expr,
                cases,
                default,
            } => CStmt::Switch {
                expr,
                cases: cases
                    .into_iter()
                    .map(|case| crate::ast::SwitchCase {
                        value: case.value,
                        body: self.prune_dead_temp_assignments_in_block(case.body, live_out),
                    })
                    .collect(),
                default: default
                    .map(|stmts| self.prune_dead_temp_assignments_in_block(stmts, live_out)),
            },
            CStmt::StructuredRegion { marker, stmt } => CStmt::StructuredRegion {
                marker,
                stmt: Box::new(
                    self.prune_dead_temp_assignments_in_stmt_live_out(*stmt, live_out),
                ),
            },
            other => other,
        }
    }

    fn prune_dead_temp_assignments_in_block(
        &self,
        stmts: Vec<CStmt>,
        live_out: &HashSet<crate::symbol::SymbolId>,
    ) -> Vec<CStmt> {
        let rewritten = stmts
            .into_iter()
            .map(|stmt| self.prune_dead_temp_assignments_in_stmt_live_out(stmt, live_out))
            .collect();
        self.prune_dead_temp_assignments_with_options_and_live_out(rewritten, true, false, live_out)
    }

}
